release-engineering/exodus-gw

docs/conf.py

Docs config seems to be copied from exodus-lambda with some stale
references left behind.

docs: fix project name/description

---

.gitignore
docs/conf.py
docs/openapi/api.html
exodus_gw/__init__.py
exodus_gw/app.py
exodus_gw/gateway.py
scripts/gen-openapi
tox.ini

Use the OpenAPI spec produced by FastAPI to generate online docs.
All endpoints will be automatically detected and included here.
Right now, this includes only the single /healthcheck endpoint,
so the docs are almost entirely empty.
The API viewer uses redoc, so it's a standalone HTML file not
embedded within the sphinx-generated docs. (I tried also
sphinxcontrib-redoc and sphinxcontrib-openapi, but they don't
seem to support OpenAPI 3.x properly.)
Note that the openapi JSON file needs to be served by a real
web server in order for redoc to work correctly, so viewing
the docs locally needs something like:
cd docs/_build/html
python -m http.server 8001
The layout of the application's modules was tweaked slightly to
better support accessing the application object from a script.

docs: add API reference page using OpenAPI & redoc

---

.github/CODEOWNERS

Ownership of this project was transferred to a new guild.
Ensure all the permanent guild members are marked as owners.

CODEOWNERS: add missing owner

---

exodus_gw/gateway.py
tests/test_gateway.py

We want to give some simple static response here, but {"200": "OK"}
isn't ideal. The response status is meant to be communicated in the
HTTP status code. Embedding in the response body as well encourages
callers to wrongly ignore the HTTP code and opens the possibility
that the two codes might not match.
Let's use the same response model as FastAPI uses by default for
errors, which is:
- no embedded response code
- a "detail" attribute with human-oriented text
This isn't a big deal since this is mainly for internal use, but
let's get it right before adding other APIs.

Tweak healthcheck response body

---

openshift/containers/exodus-gw/Dockerfile
requirements.in
requirements.txt

This container is ultimately intended for use in production, so
let's follow the advice from uvicorn docs[1] which is to use
the gunicorn server.
(I'm not aware of any specific problem with running uvicorn
directly; this is mainly a matter of following the suggested
configuration.)
[1] https://www.uvicorn.org/deployment/

containers: use uvicorn via gunicorn rather than directly

---

tests/conftest.py
tests/s3/test_manage_mpu.py
tox.ini

This PR should be merged before #13.  It will remove some unrelated changes I've pushed there.
`
(exodus) [lmilbaum@lmilbaum exodus-gw]$ pylint tests/s3/test_manage_mpu.py 
************* Module test_manage_mpu
tests/s3/test_manage_mpu.py:6:0: E0401: Unable to import 'exodus_gw.s3.api' (import-error)
tests/s3/test_manage_mpu.py:7:0: E0401: Unable to import 'exodus_gw.s3.util' (import-error)
tests/s3/test_manage_mpu.py:23:26: W0621: Redefining name 'mock_s3_client' from outer scope (line 14) (redefined-outer-name)
tests/s3/test_manage_mpu.py:62:28: W0621: Redefining name 'mock_s3_client' from outer scope (line 14) (redefined-outer-name)
tests/s3/test_manage_mpu.py:129:28: W0621: Redefining name 'mock_s3_client' from outer scope (line 14) (redefined-outer-name) …

Refactoring: Addressing various pylint/isort/flake8 errors

---

.pylintrc
exodus_gw/auth.py
exodus_gw/settings.py
tests/auth/test_call_context.py
tests/auth/test_roles.py
tests/settings/test_get_settings.py

This commit introduces the exodus_gw.auth module containing
helpers for ensuring that the current request is authenticated
and determining the associated roles.
It is designed to integrate with an existing authentication scheme
shared by various services. In summary, it works as follows:
- exodus-gw itself does not authenticate requests
- exodus-gw should be deployed behind a reverse-proxy which performs
authentication
- the authenticating proxy will add a json-in-base64 header to
incoming requests, of the form (abbreviated):
```
{
"user": {
"roles": ["some-role"],
"authenticated": true,
"internalUsername": "some-user"
}
}
```
- exodus-gw parses and trusts this header and uses it to decide
whether or not the current request is authorized.
Thus, exodus-gw supports any authentication & …

Introduce an authentication & authorization scheme

---

exodus_gw/auth.py

pylint 2.6.0 released on 2020-08-20 added a new raise-missing-from
check, which fails on this code. It appears to suggest using an
explicit "from" whenever a chained exception is raised.
In this case, raising "from None" seems most appropriate, as we
are aiming to give the user a terse HTTP error without details of
any internal exceptions (which have already been logged).

Fix pylint failure "raise-missing-from"

---

scripts/call-context

The call context header used for authentication is base64 encoded,
so it is not practical to generate header values manually, which is
annoying when trying to test the API with tools such as curl.
Add a tiny helper script for development to improve testability.
It can be used with curl as in example:
curl \
-H "X-RhApiPlatform-CallContext: $(scripts/call-context some-role)" \
http://localhost:8080/some/url

scripts: add call-context helper for dealing with auth

---

.dependabot/config.yml
.github/dependabot.yml

- migrate from old external dependabot (v1) to
github-integrated (v2)
- adjust settings to allow all updates. The former config was copied
from exodus-lambda, but we don't need to be as cautious here since
the service is not publicly accessible - it should be fine to keep
all dependencies up-to-date.

Revise dependabot config

---

.pylintrc
exodus_gw/gateway.py
exodus_gw/publish.py
test-requirements.in
test-requirements.txt
tests/test_gateway.py
tests/test_publish.py
tox.ini

/{env}/publish end point.
Run:
curl -X PUT http://localhost:8000/{env}/publish
Expected Result:
{"detail":"Created Publish Id"}
https://projects.engineering.redhat.com/browse/RHELDST-2774
Additional Information:
Changes to .pylintrc file were added due to an import-error. Following suggestion from the following KB:
https://stackoverflow.com/questions/1899436/pylint-unable-to-import-error-how-to-set-pythonpath

API end-point '/<env>/publish' created via FastAPI - request model

---

docs/api-guide.rst
docs/deployment.rst
docs/development.rst
docs/index.rst
exodus_gw/settings.py

Add one page covering deployment issues and one page covering
development.
The motivation of introducing these docs right now is to ensure
there's a place where the authentication scheme can be documented.
Other sections of the docs are light on detail at the moment.

docs: introduce deployment & development guides

---

README.md

We suggested to install requirements-dev.txt, but this repo doesn't
have that file. I don't really want to create one... let's just
list the two needed deps instead.

README: fix impossible step in development guide

---

.travis.yml

Add image build by using docker in travis-ci.

PR CI should cover container image build [RHELDST-2973]

---

exodus_gw/gateway.py
tests/test_gateway.py

Let's add a trivial endpoint which can be used to determine whether
the current user is authenticated, along with their roles. Without
this, there is no way to verify directly that the authentication
reverse-proxy is working correctly, or for a user to verify that
they were given the roles they requested, etc.
This also gives the healthcheck and whoami endpoints the same
openapi tag, so that they appear in the API docs together (as both
of them are kind of "meta APIs" relating to the service itself
rather than the exodus CDN.)

auth: add an endpoint for basic auth diagnosis

---

pyproject.toml

Dependabot is currently permitted to use the latest available
Python version. This doesn't work for us - we need pip-compile to
be run using Python 3.6, same as used in our container images,
otherwise the dependencies can be resolved incompatibly.
There is no dependabot-specific config file to control this. It
instead reads the configuration of various other python tools, and
there are several options for setting the version.
Adding it to pyproject.toml in this way seems the best option, as
we can have an explanatory comment and it does not block
development & testing of the project on later python versions.

Make dependabot use Python 3.6 while resolving deps

---

pyproject.toml

This change to pyproject.toml had the intent of causing dependabot
to choose Python 3.6 while running, without other side-effects.
Unfortunately it triggered the following crash from dependabot:
```
updater | ERROR <job_63067262> Error processing botocore (NoMethodError)
updater | ERROR <job_63067262> undefined method `downcase' for nil:NilClass
updater | ERROR <job_63067262> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.119.4/lib/dependabot/python/name_normaliser.rb:8:in `normalise'
updater | ERROR <job_63067262> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.119.4/lib/dependabot/python/update_checker.rb:294:in `normalised_name'
updater | ERROR <job_63067262> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependa …
```

Revert "Make dependabot use Python 3.6 while resolving deps"

---

docs/api-guide.rst
docs/deployment.rst
exodus-gw.ini
exodus_gw/s3/api.py
exodus_gw/settings.py
tests/conftest.py
tests/s3/test_manage_mpu.py
tests/s3/test_upload.py
tests/settings/test_get_settings.py

This commit removes the 'bucket' parameter from the s3 upload API and
it's endpoints, replacing it with 'env'. The bucket name is now
generated to match the corresponding environment defined in
exodus-gw-config.ini.

Implement environment support in upload API [RHELDST-2188]

---

examples/s3-upload

This is useful if the example does not work and you want to see
the requests/responses to figure out why.

examples: make it possible to get debug logs from s3-upload

---

requirements.in
requirements.txt

The reason for this is, as mentioned in the uvicorn 0.12.0 changelog:
> Uvicorn no longer ships extra dependencies uvloop, websockets
> and httptools as default. To install these dependencies use
> uvicorn[standard].
If those deps are not installed, that would effectively mean that
upgrading to uvicorn 0.12.0 switches us from (uvloop & httptools)
backends to (asyncio & h11) backends.
uvicorn docs[1] imply that the former are superior, so let's tweak
the deps to ensure we keep using them.
[1] https://www.uvicorn.org/settings/

deps: require uvicorn[standard] rather than just uvicorn

---

exodus_gw/s3/api.py
exodus_gw/s3/client.py
tests/conftest.py
tests/s3/test_client.py

This exception was observed from exodus-gw logs when trying to use the
upload API:
botocore.exceptions.UnseekableStreamError: Need to rewind the stream
<exodus_gw.s3.util.RequestReader object at 0x7f1869ebe9e8>, but stream is not seekable.
The reason for this is the combination of the following:
- For best performance and lowest overhead, as we receive requests,
we stream the request body to S3 without saving it in memory.
- This means there is no way to read the request body more than once,
as we haven't stored it anywhere.
- The boto library has a couple of features which cause it to attempt
reading the request body more than once. One is retrying failed
requests, which is documented, configurable & enabled by default.
Another is automatically redirecting you to the correct region if …

Avoid confusing UnseekableStreamError on request retries [RHELDST-3407]

---

exodus_gw/gateway.py
exodus_gw/s3/util.py
tests/test_exception_handler.py

To get backtraces from the server when using the upload API, responses
must be in XML format or AWS libraries will fail to parse them.
This commit overrides the HTTPException handler for exodus_gw, allowing
us to generate custom responses. Now HTTPExceptions raised by the upload
API will return XML responses. HTTPExceptions raised by all other
endpoints will fallback to the original HTTPException handler.

Return XML error responses for upload API [RHELDST-3354] 

---

.github/workflows/linting.yml
exodus_gw/__init__.py
exodus_gw/s3/__init__.py
test-requirements.in
test-requirements.txt
tests/conftest.py
tests/s3/test_upload.py

flake8 is checking the code base against coding style (PEP8). 
The PR includes a GitHub Actions workflow which runs flake8. It also includes the fixes for the errors flake8 raised in the current code base. 
I have used GitHub Actions in this PR, so that we can see how it works for us as apposed to tox+Travis.

linting with flake8 via GitHub Actions workflow

---

.pre-commit-config.yaml
pyproject.toml

Since isort standards are now enforced by CI, including it in pre-commit
will ensure related issues are dealt with locally rather than waiting
for failed Github checks.
- Added isort as a pre-commit hook
- Changed isort 'line_length' to match that of Black
- Updated hook revisions with 'pre-commit autoupdate'
- Ran 'pre-commit run --all-files' (all passed)

Add isort to pre-commit hooks

---

exodus_gw/aws/client.py
exodus_gw/aws/dynamodb.py
tests/aws/test_dynamodb.py

This commit introduces the batch_write function to write or delete
items on a DynamoDB table. A forthcoming endpoint will use this function
to "commit" publish items stored in the service database.

Introduce batch_write for DynamoDB [RHELDST-2161]

---

exodus_gw/aws/dynamodb.py
tests/aws/test_dynamodb.py

Previously, the put/delete request contructor attempted to duplicate the
"Item" key. Since duplicating keys is not permitted in Python, this
resulted in the submission of only the last item from the given list.
This change corrects this bug, creating put/delete request dicts for
every item in the given list.

Fix batch_write put/delete requests

---

docs/api-guide.rst

The location for the s3 module changed when exodus-gw was restructured
for the inclusion of additional AWS services.

Correct s3 doc reference path

---

exodus_gw/routers/gateway.py

These tags are meant to help group related APIs in docs.
The "service" tag is meant for APIs such as healthcheck and whoami,
used for inspecting or debugging the exodus-gw service itself.
Publish-related APIs should use the "publish" tag.

Fix tag for publish API

---

exodus_gw/aws/dynamodb.py
exodus_gw/crud.py
exodus_gw/routers/gateway.py
exodus_gw/settings.py
requirements.in
requirements.txt
tests/conftest.py
tests/routers/test_gateway.py

This commit introduces a new endpoint used to commit the items stored on
existing publish objects to their place in the given environment's DynamoDB
table. Retry with exponential backoff and jitter was added to the
batch_write function.
The endpoint finds the publish based on the given publish_id,
divides the publish's items into appropriate batch sizes and executes
batch_write operations. Upon failure, the entire operation is aborted
and an attempt is made to delete what was written.

Implement commit_publish endpoint [RHELDST-2161]

---

scripts/systemd/uninstall

The uninstall script seems to have had either a copy-paste or
conflict resolution error, with a few lines being duplicated.
Since we are only trying to echo a single line, usage of a heredoc
is probably overkill anyway.

devenv: fix odd message due to copy-paste error in uninstall

---

tox.ini

The intent here is to reload automatically when code has changed,
so let's have it look under the directory containing the code only.
Without this, it'll look at '.', which means it'll frequently reload
as irrelevant files are changed (e.g. it'll watch files under .tox
and then reload if you run any tox command).

devenv: tweak uvicorn args to avoid unnecessary reloads

---

docs/development.rst
scripts/systemd/exodus-gw-db.service
scripts/systemd/exodus-gw-localstack.service
scripts/systemd/exodus-gw-sidecar.service
scripts/systemd/exodus-gw-uvicorn.service
scripts/systemd/install

Make all the systemd units load an EnvironmentFile so that we can
adjust the config by writing environment variables to that file.
The two main uses for this are:
1) To remove the requirement that this project must be cloned at
~/src/exodus-gw. That path was previously hardcoded in the units
with no way of overriding; the accurate path is now generated in
the EnvironmentFile so there is no hard dependency on the
path of the checkout.
2) To provide a way to deal with port clashes, for the case where
someone is already running a service on one of the ports used by
the dev env.

dev env: use an environment file for customization

---

MANIFEST.in
setup.py

Data files alongside python packages don't get processed by
setuptools by default. This led to the SQL file containing dramatiq
schema to be missed from the python egg (and therefore the container
image).
Tweak packaging metadata to ensure the file is included.

Fix dramatiq SQL missing from exodus_gw egg & image

---

exodus_gw/models.py

One of the features included in DeclarativeBase is the implicit
generation of constructors with keywords matching attributes on
the models.  We don't need to define constructors ourselves, and
it's probably best to avoid doing that since it could lead to
inconsistencies such as forgetting an attribute in one place or
the other.

cleanup: drop unnecessary constructors from models

---

exodus_gw/aws/dynamodb.py
exodus_gw/models.py
tests/aws/test_dynamodb.py
tests/conftest.py

This commit corrects a few type inconsistencies between dicts, model
objects, and schema objects.
As the way in which put and delete requests are constructed needed to
change as a result, an 'aws_fmt' property was added to the Item model for
convenience when constructing said requests.

Fix model/schema type errors

---

docs/development.rst
scripts/localstack-dynamodb-init
scripts/localstack-s3-init
scripts/systemd/exodus-gw-localstack.service
scripts/systemd/exodus-gw-uvicorn.service
scripts/systemd/exodus-gw-worker.service

The dynamodb service in localstack seems to work just fine, so
let's enable it and start making use of it.
It's necessary to create a table before this will work. Because
the command for that is somewhat cumbersome, it was wrapped up
in a helper script; the same thing was done for s3 for consistency.
Docs now contain a few additional commands which can be used to
check the state of s3 & dynamodb within localstack.

dev env: support usage of dynamodb in localstack

---

examples/exodus-sync

This example covers a full recursive sync workflow. It works
similarly to a recursive scp or rsync, but by making use of the
exodus-gw APIs.
This can be used as a quick way to exercise the upload and publish
APIs in a development environment. With latest patches, the entire
process is basically working, but there are various TODOs to be
solved later due to some bugs and unimplemented features in
exodus-gw.

Introduce 'exodus-sync' example script

---

exodus_gw/aws/dynamodb.py
exodus_gw/routers/gateway.py
exodus_gw/settings.py
tests/aws/test_dynamodb.py
tests/conftest.py
tests/routers/test_gateway.py

Adds functionality to only commit publish items with certain file names
(configurable in settings) when all other items are successfully published.
Additionally, batch_write was simplified to a wrapper for
batch_write_items and a new function, write_batches, was introduced to
handle successive calls to batch_write.

Commit publish entry point files last [RHELDST-2161]

---

exodus_gw/aws/util.py
exodus_gw/routers/s3.py
tests/aws/test_content_md5.py

No Content-MD5 header is added to upload requests for files which have
no content. This caused a key error in our code, so a static value was
added for empty files, matching that which would be generated.

Allow upload of empty files [RHELDST-4728]

---

.travis.yml
openshift/containers/exodus-gw/Dockerfile
requirements.in
requirements.txt
setup.py
test-requirements.txt
tox.ini

Python 3.8 is available for UBI8. Let's update to that,
from python 3.6.
The motivations for this include:
- generally keeping up-to-date with modern python
- enabling usage of the contextvars feature [1] introduced in
python 3.7.  As we are using a web framework which supports
asyncio, some challenges can arise which are difficult to
solve without access to something like contextvars.
CI and tox environments were also updated to use python 3.8
and requirements files were recompiled for python 3.8, changing
the set of requirements slightly.  One dependency needed only
for python<=3.6 was dropped.
[1] https://docs.python.org/3/library/contextvars.html

Migrate container image & CI from python 3.6 => 3.8

---

docs/api-guide.rst
exodus_gw/database.py
exodus_gw/main.py
exodus_gw/routers/publish.py
exodus_gw/routers/service.py
exodus_gw/routers/upload.py
tests/app/test_db_session.py
tests/routers/test_publish.py
tests/routers/test_service.py
tests/routers/upload/test_manage_mpu.py
tests/routers/upload/test_upload.py

This commit moves various endpoints into more appropriate python
modules. It is a refactor only, with no functional impact.
The initial motivation was to ensure the publish APIs and service
APIs don't live in the same module. These endpoints are quite
unrelated and it doesn't make sense to me that their implementation,
and associated tests, were all dumped into the same 'gateway'
module.
Going a bit further, it seems reasonable to have the python modules
matching the OpenAPI tags used for the endpoints. Both the tagging
and the split between modules are ways of grouping related
functionality and there's no reason to have one grouping in the
source code layout and a different grouping in the API spec, so let's
rename the modules to make them match. This also allows applying
default tags in …

refactor: reorganize endpoints into appropriate set of modules

---

exodus_gw/main.py
exodus_gw/routers/service.py
exodus_gw/worker/broker.py
tests/routers/test_service.py
tests/worker/test_broker.py

Each HTTP request is wrapped in a transaction.
Previously, this transaction covered only the sqlalchemy ORM.
It is advantageous to also let the dramatiq broker share the
same transaction, so that when an HTTP request handler runs code
such as:
x = SomeNewObject()
db.add(x)              # persist object to DB
some_actor.send(x.id)  # enqueue dramatiq message in DB
...we can be confident that either *both* the ORM and dramatiq
changes were persisted, or *neither*.  Without this, our code would
be vulnerable to edge cases where one of these operations could
succeed and the other fail.
Although we were already using postgres for both sqlalchemy and
dramatiq, the two libraries managed their own DB connections, and
so wouldn't participate in the same transaction.
This commit fixes that by …

Share transactions between sqlalchemy and dramatiq [RHELDST-4715]

---

exodus_gw/routers/upload.py

We don't need to set tags on individual endpoints any more,
as we've set a module-wide tag. In practice, adding the tag
in both places seems to cause the API to be listed twice
in docs.

Fix duplicate tag on 'head object' endpoint

---

exodus_gw/main.py
exodus_gw/routers/publish.py
exodus_gw/routers/upload.py
exodus_gw/schemas.py

We should try to have at least some brief doc strings for most
inputs and outputs explaining what they are. This can be done
by using Path or Field objects when defining them.
A couple of Path objects were added to schemas so they can be
shared across APIs without explicitly duplicating the docs for
each API.

Extend docs for schemas and parameters

---

examples/exodus-sync
exodus_gw/crud.py
exodus_gw/models.py
exodus_gw/routers/publish.py
exodus_gw/schemas.py
tests/app/test_db_session.py
tests/routers/test_publish.py

This commit introduces the "links" attribute on Publish schema objects.
These links are URLs related to the object, served automatically by the
schema so callers needn't know how to construct the URLs themselves.

Add links to Publish objects [RHELDST-4706]

---

.pylintrc
exodus_gw/auth.py
exodus_gw/aws/dynamodb.py
exodus_gw/crud.py
exodus_gw/database.py
exodus_gw/deps.py
exodus_gw/main.py
exodus_gw/routers/publish.py
exodus_gw/routers/service.py
exodus_gw/routers/upload.py
exodus_gw/schemas.py
exodus_gw/settings.py
exodus_gw/worker/broker.py
tests/app/test_db_session.py
tests/auth/test_call_context.py
tests/conftest.py
tests/database/test_db_url.py
tests/routers/test_publish.py
tests/routers/upload/test_head.py
tests/routers/upload/test_manage_mpu.py
tests/routers/upload/test_upload.py
tests/settings/test_settings.py
tests/test_logging.py

This PR refactors the lifecycle of three kinds of objects and makes
greater usage of the dependency injection system:
- DB engine
- Settings
- Environment
The motivation behind these changes is to increase testability.
With the previous approach for handling these objects, we had
several globals constructed once at import time, and sometimes
the dependency on these globals would be hidden.
That made it more difficult to test code since you could not
simply run code with different values for Settings and expect it
to work properly - while *some* code might respect the new
settings, other code might be using globals initialized from the
old settings. That led to some hacks in tests, like one of the tests
bypassing the settings LRU cache, and the sqlite fixture having
to re-initialize the …

Refactor lifecycle of dependencies, reduce usage of globals

---

exodus_gw/models.py

It's not necessary to set unique or non-null constraints on
primary keys, because those are always unique and non-null.
This has been harmless, but this should be cleaned up for
alembic migrations to work more cleanly - otherwise, alembic
autogenerate will always detect that some uniqueness
constraints need to be created.

fixup: drop redundant constraints on primary key columns

---

docs/deployment.rst
exodus_gw/settings.py

We had disabled the usual behavior of listing all members here.
I think this was done because 'environments' is computed and can't
be set directly by env var, but this way it's too easy to forget
adding a useful setting to docs.
Let's just use the convention that we will include all documented
members in the docs, and simply don't put doc strings on those we
don't want to appear.

docs: fix most settings missing from deployment guide

---

exodus_gw/routers/publish.py
exodus_gw/routers/service.py
exodus_gw/schemas.py

- ensure all endpoints use a response model, even if it's empty;
fixes some API examples wrongly showing as "null".
- add more examples for inputs and outputs
- tweak writing style on examples to more closely match the
style used for FastAPI's built-in examples
- fix incorrect usage of Union for PUT on publish, which prevented
docs from showing both "single item" and "array of item" cases

docs: improve API reference accuracy and details

---

.pylintrc
exodus_gw/aws/client.py
exodus_gw/aws/dynamodb.py
exodus_gw/routers/publish.py
exodus_gw/worker/__init__.py
exodus_gw/worker/publish.py
tests/aws/test_dynamodb.py
tests/conftest.py
tests/routers/test_publish.py
tests/worker/test_actors.py

This commit moves the writing of items to DynamoDB to the previously
established dramatiq background worker.
As asyncio operations are incompatible with the new task delegation
method, async/await functionality was removed from the commit_publish
endpoint and the dynamodb functions and client.

Commit publishes in background process [RHELDST-4798]

---

scripts/systemd/exodus-gw-uvicorn.service
scripts/systemd/exodus-gw-worker.service

The exodus-gw dev uvicorn and worker should trust the CA cert used
for localstack. Ensure we've set REQUESTS_CA_BUNDLE pointing at
the system-wide bundle so that this works.

devenv: fix dev services unable to verify connection to localstack

---

examples/exodus-sync

Previously, exodus-sync was doing all steps almost as slow as
possible:
- upload from a single thread
- add only one item at a time to publish object
Make it faster:
- uploads of separate files happen concurrently
- when adding items to the publish, we do it in batches rather
than one request at a time
The main goal here is for exodus-sync to use the APIs in a more
realistic manner.

examples: improve exodus-sync performance

---

tox.ini

In the openshift deployment we only run a single worker process
per container. Tweak the settings in dev env to more closely
reproduce this so that the exodus-gw-worker unit behaves similarly
to one worker replica in prod.

devenv: make dev-worker run just one process

---

exodus_gw/worker/broker.py
exodus_gw/worker/middleware/__init__.py
exodus_gw/worker/middleware/schema_init.py
tests/worker/test_broker.py

Previously the dramatiq schema initialization was hooked into
'consume' on the broker.
It turns out this wasn't the best place to put it because this is
called once per queue per thread, so we'd run the initialization
code many more times than necessary, and in parallel.
We should be using middleware for this, since it's designed
specifically for this kind of "run some code on a certain event"
use-case, so let's do that. We no longer override consume(), and
instead install middleware which listens for 'process_boot'. This
happens once during startup, from the main thread.
Since we can still have multiple worker processes, it's still
possible for initialization to happen from different processes
at the same time, so let's also improve the handling of this to
cut down on misleading log …

refactor: move dramatiq initialization to middleware

---

exodus_gw/aws/util.py
exodus_gw/crud.py
exodus_gw/routers/upload.py
tests/aws/test_dynamodb.py
tests/aws/test_validate_object_key.py
tests/conftest.py

This commit adds validation for outgoing object keys, esuring all object
keys to be uploaded or published are of sha256 format.

Enforce object key format [RHELDST-4845]

---

tests/conftest.py

The sqlite driver by default will refuse to allow a connection
created by one thread to be used by another.
This doesn't play well with non-async endpoints, since they are
run via a threadpool and may be invoked from a different thread
from the final db.commit() after a request succeeds, which would
raise an exception.
Disabling this check appears to be safe, so let's do that.
Per [1], the default mode of sqlite is to be entirely thread-safe.
Per [2], the advice about disabling this check is:
> When using multiple threads with the same connection writing
> operations should be serialized by the user to avoid data corruption.
This is achieved since, although during the handling of a request we
may jump between threads to handle async vs non-async functions,
the setup with a request-scoped …

tests: disable check_same_thread with sqlite

---

exodus_gw/dramatiq/broker.py
exodus_gw/dramatiq/consumer.py
exodus_gw/dramatiq/middleware/__init__.py
exodus_gw/dramatiq/middleware/scheduler.py
exodus_gw/migrations/versions/a60131dd10c4_.py
exodus_gw/models/dramatiq.py
exodus_gw/settings.py
exodus_gw/worker/__init__.py
exodus_gw/worker/scheduled.py
requirements.in
requirements.txt
tests/dramatiq/test_broker.py
tests/dramatiq/test_scheduler.py
tests/worker/test_cleanup.py

This commit implements middleware for having actors scheduled by
cron-style rules. It will be used for periodic cleanup.
Scheduled actors work as follows:
- use @dramatiq.actor(scheduled=True) to declare actor
- Settings class must have a "cron_<actor_name>" key which holds
a cron-style rule (e.g. "0 */2 * * *" for "every two hours, at 0
past the hour)
- middleware wraps the actor in a function which arranges for itself
to be called every Settings.scheduler_interval minutes, and only
invokes the real actor if the cron rule triggered since the last
run
- middleware ensures one call to this wrapped actor is enqueued during
worker startup.
The end result is that the actor will be automatically executed
approximately according to the associated cron rule.
This is expected to be used by a …

Introduce the concept of scheduled actors

---

exodus_gw/auth.py
exodus_gw/deps.py
exodus_gw/routers/service.py
tests/auth/test_call_context.py
tests/auth/test_roles.py
tests/routers/test_service.py

In the case of both endpoints, and functions used with Depends, if they
don't use any blocking functionality then we should mark them as
async.
We should do this because otherwise FastAPI is pessimistic: it assumes
any non-async function might block, and so runs it in a threadpool.
This works but is rather wasteful to do this for every dependency
when not needed.

Add missing 'async' in various places, reduce unneeded threads [RHELDST-4857]

---

examples/exodus-sync

Since we have resolved the problem with https requests hanging in
boto, we should now get into the habit of using https and client
certs/keys by default. Let's also exercise a few of the other APIs
in this example, particularly 'whoami' so the cert/key can be
easily confirmed as working (or not).
Right now, this doesn't really affect anything, but we will soon
start enforcing appropriate roles on each endpoint. Once that
happens, usage of https will become more or less mandatory.

examples: start using https & certs in exodus-sync

---

exodus_gw/main.py
exodus_gw/routers/publish.py
tests/async_utils.py
tests/conftest.py
tests/routers/test_publish.py

sqlalchemy's session is not designed for use with async. Using any
of its blocking methods from within an async function could block
the entire service for the duration (e.g. if a db.commit() in one
request were to take five seconds, the service would effectively
hang and not process any other requests for those five seconds).
Fix it so that usage of the session never blocks the main thread.
Achieved in two ways:
- for endpoints using the DB, they simply shouldn't be defined with
async. This will make FastAPI run them via a threadpool.
- for the DB usage within middleware, which has to be async,
explicitly call the close/commit functions via a threadpool.
This kind of bug would be easy to reintroduce, as the symptoms
are only some mysterious slowness which is probably too slight
to notice …

Fix usage of blocking DB session from async functions [RHELDST-4857]

---

exodus_gw/migrations/versions/854e06069e65_.py
exodus_gw/migrations/versions/a60131dd10c4_.py

Migrations would fail with:
psycopg2.errors.DependentObjectsStillExist: cannot drop constraint publishes_pkey on table publishes because other objects depend on it
DETAIL:  constraint items_publish_id_fkey on table items depends on index publishes_pkey
Our usage of recreate='always', to work around an issue on older
versions of sqlite, triggered the problem. As that is an
sqlite-specific fix, let's apply it *only* when using sqlite and
otherwise leave the parameter at the default value of "auto".

Fix DependentObjectsStillExist when running migrations on postgres

---

examples/exodus-sync
exodus_gw/aws/dynamodb.py
exodus_gw/migrations/versions/55d4111a0e09_.py
exodus_gw/models/publish.py
exodus_gw/routers/publish.py
exodus_gw/schemas.py
exodus_gw/worker/publish.py
tests/aws/test_dynamodb.py
tests/conftest.py
tests/routers/test_publish.py
tests/test_models.py
tests/worker/test_actors.py

This commit removes the from_date attribute from the Item model and
schema so users are unable to set this field themselves, as there is
currently no use-case for them to do so.
The from_date attribute is still required by the DynamoDB table,
however, so it is programmatically set to the datetime at which
the item's parent publish is committed.

Remove from_date Item attribute [RHELDST-4868]

---

exodus_gw/models/publish.py
exodus_gw/schemas.py
exodus_gw/settings.py
exodus_gw/worker/scheduled.py
tests/conftest.py
tests/dramatiq/test_scheduler.py
tests/migrate/test_db_migrate.py
tests/routers/test_publish.py
tests/routers/test_service.py
tests/test_models.py
tests/worker/test_actors.py
tests/worker/test_cleanup.py

Previously we had a stubbed out scheduled cleanup task, as we
needed some more columns on the model before it could be
implemented.
As those are now available, let's fill in the implementation of
the cleanup task. It covers steps:
- find & fix anything with missing timestamps
- mark anything which is obviously abandoned or stuck as failed
(for 2 days by default)
- delete anything which has been in a terminal state for long
enough (2 weeks by default)
The thresholds are configurable via settings.

Implement scheduled cleanup task [RHELDST-4843]

---

exodus_gw/auth.py
exodus_gw/routers/publish.py
exodus_gw/routers/upload.py
scripts/systemd/exodus-gw-sidecar.service
scripts/systemd/install
tests/conftest.py
tests/routers/test_publish.py

Users must now possess the appropriate role to request uploads or
publishes to a particular environment, e.g., "stage-blob-uploader" to
upload to the "stage" environment.
The development environment was updated to automatically authorizate
users for the "test" environment.

Require authorization for upload and publish APIs [RHELDST-4729]

---

exodus_gw/routers/upload.py

- change name from "Request head object" to "Get object metadata" to
fit more closely with names for other endpoints
- fill a bit more in the description of this API, explaining that
the main purpose is to test whether an object exists, which might
not be obvious
- fill in response descriptions to make it clear that a 404 response
is the expected way for the service to communicate that an object
doesn't exist

docs: tweak API docs for "HEAD object"

---

exodus_gw/main.py

I think we've reached the point that we should commit to a stable
API, so let's set the version to 1.0.0 and remove the warning from
docs. The API has been stable for a little while now, and since
we now have code in exodus-rsync making use of it, it's time to
start taking backwards-compatibility seriously.

Set API as stable

---

examples/s3-upload

It requires you to have a valid certificate and key produced by RHCS
for calling example/s3-upload.

Add auth support for s3-upload

---

.github/workflows/ci.yml

The push-docs script, when passed 'github.token', reports "No
such device or address". This commit replaces the token with a personal
access token, which was the method used with Travis.ci.

Replace push-docs' GITHUB_TOKEN with access token [RHELDST-5390]

---

scripts/push-docs

Since we moved from Travis to Actions, the push-docs step started
to fail after merging if docs haven't changed since last push.
The behavior of the script didn't change, but it seems that Travis
simply ignored the exit code of an "after_success" command since
the job had already succeeded by that point. Actions works a bit
different and it's important to exit with a 0 exit code in this
case.

Fix push-docs failing when docs haven't changed

---

.github/workflows/ci.yml
tox.ini

When switching to Github actions from Travis CI, the method of
publishing coverage data to coveralls changed from using
coveralls-python package to a Github action.
This commit reverses that switch, returning to coveralls-python for
reporting coverage, as the Github action alternative has demonstrated
inaccurate reporting in another project.

Return to coveralls-python for reporting coverage

---

.github/dependabot.yml

We're trying a new "scheduled pip-compile" workflow rather than
dependabot, see recently introduced workflow files.

Drop dependabot.yml

---

.github/workflows/pip-compile.yml

Addresses the following issues in scheduled pip-compile (see also https://github.com/release-engineering/exodus-gw/commit/ce0e58a1a2a5d9976f0ef2e193de09c1ee58d94e for more explanation):
- when compiling test-requirements.txt, we really need to use both requirements.in and test-requirements.in together.  It's needed to ensure that the generated requirements end up being compatible with *both* of the inputs.
- we need to use a non-default token when creating the PR.  If not, it runs into the rule from https://docs.github.com/en/actions/reference/events-that-trigger-workflows: "When you use the repository's GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run".  That means, if the repo's CI is based on …

Fix CI issues with scheduled pip-compile

---

requirements.txt
test-requirements.txt

This reverts commit 656e2c759d5b8e9390677ed83b00198b46fba96e.
That automated dependency update was wrongly merged even though it
failed CI, because we had missed branch protection rules in the repo.
We should not update alembic currently due to
https://github.com/sqlalchemy/alembic/issues/900.

Revert dependency update (alembic bug)

---

exodus_gw/migrations/versions/c46641b76073_.py
exodus_gw/models/publish.py
exodus_gw/routers/publish.py
exodus_gw/schemas.py
tests/routers/test_publish.py
tests/test_models.py
tests/worker/test_cleanup.py

Previously, exodus-gw accepted items that had a web_uri and a valid
object_key. Soon exodus-rsync will send items with a link_to value
instead of an object_key and the resolution of the object_key will be
handled within exodus-gw based on the link_to path. With this commit
exodus-gw accepts items that have either a link_to or an object_key.

Accept publish items with link_to or object_key [RHELDST-8586]

---

exodus_gw/models/publish.py
exodus_gw/routers/publish.py
tests/routers/test_publish.py

Now that items with either object_key or link_to are accepted,
we can use link_to to find the correct object_key from among the other
publish items.
This commit adds the resolve_links function to the publish model.
If the function doesn't find an item with a web_uri that maches the
link_to of the target item, an error of code 400 is raised.

Resolve item object_keys from link_to [RHELDST-8587]

---

.pylintrc
exodus-gw.ini
exodus_gw/aws/dynamodb.py
exodus_gw/aws/util.py
exodus_gw/settings.py
tests/async_utils.py
tests/aws/test_dynamodb.py
tests/aws/test_uri_alias.py
tests/conftest.py
tests/routers/test_publish.py
tests/settings/test_settings.py

Because exodus-lambda maps uri aliases before looking them up on the
Exodus CDN, we must do the same when publishing to it. This commit
implements code which do just that while constructing DynamoDB write
requests.
Previously, exodus-gw would publish an item with a web_uri like
"/content/origin/rpms/some/file.iso". If exodus-lambda then receives a
request for "/content/origin/rpms/some/file.iso", it will resolve the
origin alias and futilely look for an item with a web_uri of
"/origin/rpms/some/file.iso".

Resolve origin aliases before publishing [RHELDST-8582]

---

examples/exodus-publish

This example makes it a bit easier to create and commit publish objects,
as it is somewhat cumbersome to do that otherwise (e.g. using curl + jq).
It can be used something like this:
PUBLISH=$(examples/exodus-publish --url ... new)
exodus-rsync --exodus-publish=$PUBLISH src1 exodus:/dest
exodus-rsync --exodus-publish=$PUBLISH src2 exodus:/dest
examples/exodus-publish commit
The idea is that, since Pub is not yet ready to manage the publish
objects for us, this script provides a reasonably convenient way to
create & commit publishes meanwhile.

Introduce exodus-publish example/helper

---

tests/app/test_db_session.py
tests/routers/test_common.py

There are a few invariants which all endpoints should try to satisfy in
order for the API to work correctly and consistently. Add a test which
will check these on all endpoints, to protect against mistakes when
introducing a new endpoint.
One existing test needed some minor refactoring, as it would otherwise
leave a test route installed on app which would fail test_common.

tests: add a test covering common behaviors for every endpoint

---

tests/worker/test_deploy.py

When checking the message delay we should not do a precise
millisecond-level comparison like this. The message handling isn't
instant and it is possible for the delay to be slightly higher than the
specified value.
Add a 1 second leeway onto the comparison to stabilize the test.

tests: fix slightly flaky test_deploy_config

---

exodus_gw/routers/publish.py
exodus_gw/schemas.py
tests/routers/test_publish.py

In order to support the explicit deletion/hiding of content on exodus
CDN, it should make exodus-gw allow setting the object_key to the string
"absent" on uploaded publish items.

Support publish of 'absent' items [RHELDST-9953]

---

docs/development.rst
scripts/launch-devenv
scripts/localstack-dynamodb-config-init
scripts/localstack-init

When we introduced the second DynamoDB table in order to hold config,
the instructions and scripts here were never updated to cover creation
of it. Add it now.

dev env: update scripts/instructions for config table

---

scripts/systemd/exodus-gw-db.service
scripts/systemd/exodus-gw-localstack.service
scripts/systemd/exodus-gw-sidecar.service

These units were originally created by "podman generate systemd"
which inserted a KillMode=none directive. That value of KillMode
was deprecated by systemd and will be removed in the future.
This commit updates the units to be aligned with podman's fix for
the issue in https://github.com/containers/podman/issues/8615,
which was to drop KillMode and add TimeoutStopSec.

dev env: fix deprecated KillMode=none

---

scripts/systemd/exodus-gw-cert.service
scripts/systemd/exodus-gw-sidecar.service

The dev env runs sscg in order to create certs.
It previously worked by always running sscg but tolerating an exit code
of 17, which was sscg's documented code for "output already exists".
Let's change it to instead only run sscg if one of the outputs doesn't
exist or is empty, because:
- the sscg "ERROR: File exists" message can be confusing and lead the
developer to think that something has gone wrong.
- it is potentially useful to be able to recover from "cert exists but
is empty", as this has been observed to happen at least once (though I
don't know why).
Additionally, the duplication of sscg between exodus-gw-cert and
exodus-gw-sidecar has been removed so that this logic is only in one
place.

dev env: tweak sscg execution conditions

---

docs/development.rst
scripts/localstack-init

It seems that the aws commands used in the localstack-* init scripts
were using the environment's default profile (or the profile set by the
user in AWS_PROFILE).
In a clean environment, that's a problem since no profile will exist;
and even though our docs suggested creating a "test" profile, these
scripts didn't attempt to use that profile, so it wouldn't help unless
the caller explicitly set AWS_PROFILE=test.
Let's make it a bit more robust:
- localstack-init will check for a 'test' aws profile and create it if
missing.
- localstack-init always attempts to use the 'test' aws profile.

dev env: create & enforce 'test' aws profile during localstack setup

---

exodus_gw/main.py
exodus_gw/routers/cdn.py
exodus_gw/routers/deploy.py

- in the main API overview, add links for the deploy & cdn APIs.
- on the FastAPI app object, make sure we add the openapi_tag objects
from the deploy/cdn modules. Without this, the module-level doc
strings never end up in the rendered docs.
- revise those module-level doc strings so they don't repeat info in the
doc string on each endpoint.
- redirect: avoid duplicate docs between the GET and HEAD methods
- redirect: flesh out some missing details, including URL parameter,
status code and location header.
- redirect: revise the description to focus more on the purpose of the
endpoint, rather than how it's implemented.
- deploy: tweak the response summary (replacing default "Successful
Response" with "Deployment enqueued") to be consistent with the
established style.
- deploy: document …

docs: various API doc improvements for recent features

---

scripts/systemd/exodus-gw-localstack.service

While exodus-gw itself doesn't use secretsmanager, it is used from other
exodus components. Let's enable it so those components can be tested
against this localstack.

dev env: enable secretsmanager in localstack

---

exodus_gw/deps.py

Changes in the dependency tree of pylint have affected precisely which
line needs to have a "pylint: disable" comment here. Let's just move it
to file level, which should remain stable over time

Fix a failure with newest pylint

---

exodus_gw/routers/publish.py

The docs had a sentence explaining that behavior is not truly atomic,
followed by an explanation of how we "ensure the atomicity". It seems
confusing. Reword it to more accurately reflect the truth of
near-atomicity.

docs: tweak references to atomicity

---

exodus_gw/deps.py
exodus_gw/main.py
exodus_gw/routers/upload.py
exodus_gw/settings.py
tests/aws/test_content_md5.py
tests/routers/upload/test_head.py
tests/routers/upload/test_manage_mpu.py
tests/routers/upload/test_upload.py

This commit introduces caching for AWS S3 clients to reduce overhead
of the upload API.

Reuse S3 connections [RHELDST-4926]

---

tests/auth/test_call_context.py
tests/auth/test_roles.py
tests/aws/test_client.py
tests/aws/test_request_reader.py
tests/routers/test_service.py
tests/routers/upload/test_head.py
tests/routers/upload/test_manage_mpu.py
tests/routers/upload/test_upload.py
tests/test_exception_handler.py
tox.ini

pytest-asyncio for some time generates the following deprecation
warning:
The 'asyncio_mode' default value will change to 'strict' in future,
please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto'
in pytest configuration file.
Do what it says. 'auto' is recommended (as long as you aren't mixing
multiple asyncio test frameworks together), so we'll use that. This
allows the asyncio marker to be dropped from all the tests.

tests: fix pytest-asyncio deprecation warning

---

.pre-commit-config.yaml
exodus_gw/models/publish.py
tests/routers/test_publish.py

Previously this method loaded every item on the publish, storing them in
memory for its duration. The number of these items can realistically
reach into many hundreds of thousands, approaching a million.
This commit refactors the method to use a querying approach to store
only the items that it needs to operate on -- those with non-empty
link_to fields -- and load only the URI and object key of the
corresponding items. These changes should significantly reduce the
impact this method has on system memory.

Improve Publish model's resolve_links [RHELDST-11634]

---

exodus_gw/deps.py
exodus_gw/main.py
tests/conftest.py
tox.ini

There were two problems here with client shutdown:
1. \_\_aexit\_\_ is an async method and the result needs to be awaited. Fix
that, and adjust test suite arguments to turn some warnings into
errors so that the same mistake can't happen again.
2. \_\_aexit\_\_ needs some arguments. Calling it with no arguments will
crash. Fix that, and fix the inaccurate mock which allowed tests to
miss the error.

Fix shutdown of S3 clients after connection pool introduced

---

tests/routers/upload/test_manage_mpu.py

The mock request here was an AsyncMock.
The problem with this is that it causes *all* automatically generated
methods to behave as async. This is not realistic: on a real Request
object, the 'body' method is async, but most others are not. This could
cause a "coroutine ... is never awaited" error if the code under test
was changed to access any new attributes on request.
Fix it by making it a non-async Mock and making the body method
explicitly async.

tests: fix an inaccurate mock

---

exodus_gw/models/publish.py
tests/routers/test_publish.py

When querying for publish items with link_to set, all others were
expected to have link_to=None. However, clients are able, and often do,
set link_to to an empty string rather than leaving it unset or None.
This commit improves the query to account for this by reading NULL/None
values as empty strings and filtering those instead.

Filter null and empty strings in Publish's resolve_links [RHELDST-11634]

---

exodus_gw/dramatiq/broker.py
exodus_gw/dramatiq/middleware/__init__.py
exodus_gw/dramatiq/middleware/db_ready.py

Currently, we consider the two exodus components as "web" and "workder".
* the web component is responsible for running DB migrations during the
initialization of the web app
* the worker component does not run DB migrations, it simply assumes the
DB is up-to-date.
When booting up worker, the web component initialization can be
unfinished. This patch adds DB check when booting up a worker.

Fix exodus-gw worker DB errors on startup [RHELDST-11593]

---

exodus_gw/dramatiq/broker.py
exodus_gw/logging.py
exodus_gw/main.py
exodus_gw/settings.py
tests/dramatiq/test_broker_inits_loggers.py

The Settings class takes settings from two sources: environment
variables and exodus-gw.ini. All logging config lives in the INI
file.
Problem: the proper loading of settings and initialization of loggers
was hooked into the WSGI app startup and not used for the worker
component, which would simply construct a 'Settings()'. This meant any
non-env-var config would be silently missed by the worker, including
configuration of the loggers.
Hence, adjusting the log level would have no effect for the worker process.
Fix it by ensuring that the worker loads settings properly and
initializes loggers on startup. The logger initialization shares code
with the web component. A minor change to .ini file loading was also
added to improve testability, as it was not previously possible to make
a test …

Fix logging config not respected by worker [RHELDST-12333]

---

docs/development.rst
scripts/systemd/install

Because no profile was specified, the commands as documented here might
not actually work - it would depend on the state of the caller's AWS
config files.
We know that a profile named 'test' should exist because
scripts/localstack-init creates one if needed, so let's adjust the
commands to refer to it. It should make the commands a bit more reliable
across environments.

dev env: tweak suggested awscli commands

---

docs/development.rst
scripts/systemd/exodus-fakefront.service
scripts/systemd/install
scripts/systemd/restart
scripts/systemd/uninstall

When running the exodus-gw components locally it is convenient to also
run fakefront from exodus-lambda in the same way. This allows easy
access to published content without relying on DynamoDB table scans or
similar.

dev env: integrate support for fakefront

---

exodus-gw.ini
tests/routers/test_cdn.py

The test env in this exodus-gw.ini is primarily used for the development
environment. Rather than pointing it at a bogus cloudfront URL which will
never work, let's point it at the fakefront instance deployed in that
development environment so the CDN redirect endpoints have a chance at
working out of the box.

dev env: tweak exodus-gw.ini cdn_url for fakefront

---

openshift/containers/exodus-gw/Dockerfile

It will use these python package:
- python3-3.9.10-2.el9.x86_64
- python3-devel-3.9.10-2.el9.x86_64

Upgrade exodus-gw to ubi9 [RHELDST-12689]

---

exodus_gw/dramatiq/broker.py
exodus_gw/dramatiq/middleware/__init__.py
exodus_gw/dramatiq/middleware/log_actor.py
tests/dramatiq/test_worker.py

Add a new middleware which will arrange for all log messages produced
within an actor to be prefixed with at least the actor's name, plus
task/publish ID being processed where possible.
This ensures that every log message can be traced back to a particular
publish/task which makes it much easier to quickly find relevant logs,
without requiring the logging statements to explicitly log the task
being handled.
Here's an example of the impact of this change:
```
-Items successfully written
+[commit c3234df2-cdaf-4df1-aa1e-b360fd68f8a1] Items successfully written
```
This change was done in preparation for RHELDST-12449 which has some
requirements around logging.

logging: prefix log messages with current actor

---

exodus-gw.ini
tests/test_logging.py

This config file is used both when running tests and from the exodus-gw
dev env.
The log levels requested here were presumably arbitrary for testing,
but they don't make sense for the dev env or in general: they set the
exodus-gw logger to *less* verbose than all other loggers, which is the
opposite of what we'd want in practice.
Flip it around so the root and exodus-gw loggers use more appropriate
levels (also matching the config we actually use for deployment), and
fix up the one affected test.

exodus-gw.ini: use more appropriate log levels

---

exodus_gw/migrations/versions/5bd0b38df850_.py

When both the "items" and "publishes" tables contain some data, then
only deleting the existing records in "publishes" table without cleaning
"items" table, it will violate the item's foreign key constraint
pointing back at publishes.
This commit adds the "items" table cleaning.

Fix the migration failure on startup [RHELDST-13372]

---

exodus_gw/alembic_upgrade.py
setup.py
tests/test_alembic_upgrade.py

Because a DB migration can take up to 15 minutes, we decide to decouple
it from the gunicorn initialization.
This commit adds a new script for calling alembic upgrade.

Add alembic_upgrade.py for DB migration [RHELDST-13374]

---

exodus_gw/routers/publish.py
tests/routers/test_publish.py

This commit adds a check and error to commit and update_publish_items, making it clear when no publish is returned from the database.

Check publish objects from database before attempting to use them

---

requirements.in
requirements.txt
test-requirements.txt

This version of repo-autoindex is expected to significantly reduce memory usage when indexing a large repo, so let's ensure we always use this version or newer.

Use repo-autoindex>=1.0.2 for reduced mem usage [RHELDST-14338]

---

exodus_gw/database.py

Exodus-gw now uses the SQLAlchemy pool_pre_ping option [1] to detect and recover from a broken DB connection [2] at the beginning of a request.
[1] https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_pre_ping
[2] https://docs.sqlalchemy.org/en/14/core/pooling.html#dealing-with-disconnects

Enable pool_pre_ping on db connections [RHELDST-13928]

---

exodus_gw/main.py
exodus_gw/settings.py
tests/app/test_db_session.py

Exodus-gw now uses the sqlalchemy pool_pre_ping option to detect and recover from a broken DB connection at the beginning of the request. To accommodate for a broken DB connection within the request, exodus-gw wraps select endpoints in a "retry" decorator.

Make exodus-gw resilient against postgres connection drops [RHELDST-13928]

---

exodus_gw/settings.py
tests/app/test_db_session.py

Fixes errors from two sources:
1) mypy previously applied an implicit Optional to default arguments
declared as None. It no longer does this. Explained at
https://github.com/hauntsaninja/no_implicit_optional#whats-going-on
2) In recent changes to test_db_session.py, code was added to
dynamically set a call_count attribute onto a declared function to
track whether it had been called earlier. There is no simple way to
make the type checker understand this.
Rewrite it slightly. All endpoints already have access to generic
request and app scoped 'state' objects, so just use that instead of
storing it on the function object. Also cleaner since the value does
not have to be explicitly reset anywhere, since these state objects
are already scoped appropriately.

Fix typing errors on latest version of mypy

---

examples/s3-upload

Metadata will soon be supported by exodus-gw on upload, so it'd be good if this example supports it too. Can be used to verify that metadata survives a round-trip and that S3 & exodus-gw behavior is compatible.
Example usage against localstack from dev env:
env AWS_PROFILE=test \
examples/s3-upload --endpoint-url https://localhost:3377 \
--env my-bucket \
README.md \
--meta mykey=myval --meta otherkey=otherval

examples: extend s3-upload with metadata support

---

scripts/systemd/exodus-gw-db.service

When starting up all units it seems that it was possible for the following to happen:
- exodus-gw-db service is marked active, but hasn't yet started to accept connections
- exodus-gw-uvicorn starts up, fails to initialize because it can't connect to DB
- exodus-gw-db starts to accept connections; but because exodus-gw-uvicorn uses hot reload, it will not automatically exit and be restarted by systemd, so the service remains broken indefinitely (could be fixed by manually restarting that service)
In this commit we add a post-start command to exodus-gw-db which waits for the expected TCP port to become open. It should make the above less likely to happen as the startup of exodus-gw-uvicorn will be delayed until the DB is apparently ready for use.

dev-env: mitigate race condition during service startup

---

exodus_gw/aws/util.py
exodus_gw/routers/upload.py
exodus_gw/settings.py
tests/routers/upload/test_head.py
tests/routers/upload/test_manage_mpu.py
tests/routers/upload/test_upload.py

When migrating content in the future, we plan to store information on uploaded objects. This commit allows users to set metadata via headers for fields defined in settings and HEAD requests will now return metadata stored with the object.

Support metadata on S3 uploads [RHELDST-14181]

---

.safety-policy.yml

Our own code doesn't trigger any of the mentioned leaks. It also seems that an upgrade to sqlalchemy 2.x may require more effort than a typical upgrade, so a new issue has been filed for it.

safety: do not block on PVE-2022-51668 for now [RHELDST-15252]

---

exodus_gw/routers/publish.py
tests/routers/test_publish.py

When commit_publish is called multiple times or retried, it will now return the task to which the publish was previously assigned rather than raising an exception (because the publish is not currently "PENDING").

Make commit_publish idempotent [RHELDST-15029]

---

requirements.in

We already know that we aren't yet compatible with sqlalchemy 2.x and filed an issue to work on that.
Given that sqlalchemy 2.0.0 was recently released, our weekly dependency updates now try to make use of it and will fail CI. Request an older compatible version until we fix the compatibility issues.

Avoid sqlalchemy 2.x for now [RHELDST-15252]

---

exodus_gw/routers/publish.py
tests/routers/test_publish.py

Previously, when querying publishes from the service db, we only filtered by publish IDs. This commit adds env to the query filter to ensure we're only manipulating publishes belonging to the service environment used.

Add 'env' to publish queries [RHELDST-15336]

---

exodus_gw/migrations/versions/6461bad8ed91_.py
exodus_gw/routers/publish.py
tests/routers/test_publish.py

When update_publish_items is called, if the item's web_uri already exists on that publish, it will now update the item in db rather then adding a new item.

Make update_publish_items idempotent by no duplicating web_uri [RHELDST-15028]

---

.github/workflows/pip-compile.yml
tox.ini

Make the following changes to the pip-compile github action:
- run it via tox. Most of our repos using pip-compile already do this; the only reason it wasn't done here is that this was one of the earliest of our repos to adopt pip-compile and there was not yet an established convention.
The primary advantage to this is that one can simply run "tox -e pip-compile" locally when needed.
- Use the backtracing resolver (which will be the default in 7.0.0). With the legacy resolver, pip-compile currently fails with:
There are incompatible versions in the resolved dependencies:
packaging>=22.0 (from black==23.1.0->-r test-requirements.in (line 2))
packaging>=21.0 (from sphinx==6.1.3->-r test-requirements.in (line 10))
packaging<22.0,>=21.0 (from safety==2.3.5->-r test-requirements.in (line 13)) …

Refactor and fix pip-compile

---

.pre-commit-config.yaml
examples/exodus-sync
examples/update-config
exodus_gw/aws/util.py
exodus_gw/models/publish.py
exodus_gw/models/service.py
test-requirements.in
tox.ini

"tox -e static" previously ran the black autoformatter using a version managed by pip-compile.
Problem: pre-commit also runs black, but this uses the version defined in the pre-commit config. If there are any differences in the black code style between the two versions of the tool, they will not both be able to pass.
This recently blocked dependency updates for this repo because a new release of black is available which has some incompatibilities with the version used by pre-commit.
Rather than trying to keep both versions in sync, it makes more sense to apply the tool in just one place; so let's drop it from tox & github actions and rely only on pre-commit.ci to both run the tool and manage the version of the tool.
This commit includes an update to the pre-commit hook versions so that …

Drop black from github actions CI

---

exodus_gw/worker/publish.py

With latest versions of all packages, mypy has started to complain:
exodus_gw/routers/publish.py:304: error: Missing positional argument
"settings" in call to "send" of "Actor"  [call-arg]
There is no actual type error here - we have dramatiq middleware to insert an instance of 'Settings' to any actor with a settings argument. However, mypy is not aware of that.
It can be easily fixed by declaring a default, so just do that. In practice we never expect the default to be used and this is only to help mypy.

Fix mypy error with latest versions of dependencies

---

.github/renovate.json
.github/workflows/ci.yml
openshift/containers/exodus-gw/Containerfile

To ensure exodus-gw has all available security patches, this commit;
- Locks UBI base image
- Adds renovate bot config, allowing automated base image updates
- Adds 'update' command to build
This commit also renames "Dockerfile" to "Containerfile" in openshift/containers/exodus-gw/.

Ensure exodus-gw image is updated [RHELDST-15305]

---

exodus_gw/worker/scheduled.py

This commit swaps the order of deleting a publish object and deleting all of its items to fix the ForeignKeyViolation error.

Fix the ForeignKeyViolation by swapping the deletes [RHELDST-15252]

---

openshift/containers/exodus-gw/Containerfile

platform-sidecar is now deployed with a 15 second maxIdleTime for connections. This change gives more headroom for said connections.

Extend gw keep-alive for platform-sidecar idle time [RHELDST-17390]

---

exodus_gw/routers/cdn.py
exodus_gw/schemas.py
exodus_gw/settings.py
tests/routers/test_cdn_access.py

This endpoint allows users in the {env}-cdn-consumer role to generate cookies for accessing exodus-cdn with their preferred expiry date (up to a predefined maximum).
By having an API which can be used programmatically to generate cookies, exodus-cdn users can implement a fully automated workflow to rotate their cookies periodically. This helps shift responsibility for handling cookie expiry from exodus-cdn owners to exodus-cdn users.

Introduce cdn-access endpoint [RHELDST-17781]

---

scripts/systemd/exodus-gw-sidecar.service

The cdn-access endpoint won't be usable in the dev-env unless the current user is listed in the approprate role, so make sure to do that.

dev-env: ensure role is set up for cdn-access [RHELDST-17781]

---

exodus_gw/aws/dynamodb.py
exodus_gw/worker/progress.py
exodus_gw/worker/publish.py
tests/aws/test_dynamodb.py
tests/worker/test_progress.py
tests/worker/test_publish.py

Previously during DynamoDB writes we only generated log messages such as "Items successfully written" per batch, which doesn't help much understanding the progress.
Let's add some new logging which makes it easier to track the progress and performance. An example of the new log messages generated during commit (maximum of one log message per 5 seconds):
Writing phase 1 items: 775 (of 10000) [ 8% ] [6.9 p/sec]
Inspired by performance issues observed testing against localstack. These logs should make it easy to directly compare the performance (items per second) between localstack and each AWS environment.
The old log message still exists but was downgraded to DEBUG.

Log progress info during DynamoDB writes

---

scripts/systemd/exodus-gw-localstack.service

Use the same localstack image as used in PiAAS for improved accuracy.
There were some backwards-incompatible localstack changes which needed minor adjustments to the deployment: persistence/DATA_DIR handling changed, and SSL cert handling changed.
Due to those changes, this commit may potentially require a clean reinstall of the dev-env.

dev-env: update localstack version

---

exodus_gw/auth.py
tests/auth/test_roles.py

If a user tries and fails to access an endpoint due to missing roles, according to the "events of interest" requirements we should probably be logging that.

logging: add success/fail logs to authorization checks

---

exodus_gw/auth.py
tests/auth/test_roles.py
tests/routers/test_publish.py

I'm not sure why base_url was used here, but it was not the correct property. Per [1], request.base_url.path is simply always "/" and not the path actually being accessed.
request.url is the correct property to use here.
[1] https://github.com/encode/starlette/blob/15d9350eed9437bcb0683e2c24cd4cfbf985ed7e/starlette/requests.py#LL102C16-L102C16

logging: fix logged path always "/" during auth

---

exodus_gw/aws/dynamodb.py
tests/worker/test_deploy.py

deploy-config has been broken since d2939b30c6fb14c, which changed the signature of DynamoDB.batch_write but didn't update one of the calls to that method, resulting in:
TypeError: batch_write() takes 2 positional arguments but 3 were given
Additionally, as all tests of the deploy_config actor mocked out DynamoDB.batch_write, tests didn't detect the issue and instead incorrectly passed.
This commit fixes the crash and also changes one of the tests to work at a lower level (mocked boto) rather than mocking our DynamoDB helper class. This helps ensure the test would be able to detect similar problems in the future.

Fix deploy-config tasks always crashing [RHELDST-18195]

---

exodus_gw/aws/dynamodb.py
tests/aws/test_dynamodb.py

The backoff library does not log retry attempts by default [1].
"By default, backoff and retry attempts are logged to the ‘backoff’
logger. By default, this logger is configured with a NullHandler, so
there will be nothing output unless you configure a handler.
[...]
It is also supported to specify a Logger (or LoggerAdapter) object
directly."
Now, the _batch_write backoff decorator has been configured to log
backoff events for any EndpointConnectionErrors encountered during
batch writes. This way, engineers can more easily identify when
retries due to EndpointConnectionErrors are attempted during batch
writes.
The backoff attempts are logged at DEBUG using the exodus-gw logger.
[1] https://pypi.org/project/backoff/

Log backoffs on EndpointConnectionErrors [RHELDST-18585]

---

exodus_gw/auth.py
exodus_gw/main.py
tests/routers/test_common.py

Our security standards require us to log "login" events.
Although exodus-gw does not technically provide a "login" endpoint, we have defined a login event as, "when platform-sidecar accepts a presented cert as valid during TLS handshake."
Unfortunately, the platform-sidecar logs do not seem to indicate whether a certificate has been provided with the request in question.
exodus-gw already produces an "auth" log containing the requested path, username, and roles when an endpoint that requires authorization has been requested. Though, exodus-gw also provides read-only endpoints which do not require authorization. It technically possible for a user to provide a cert (and for platform-sidecar to consider it valid) to endpoints which do not require authorization. A log was previously not …

Log "login" events [RHELDST-19460]

---

exodus_gw/auth.py
tests/routers/test_common.py

The OpenShift readiness and/or liveness probes request the '/healthcheck' endpoint every every few seconds.
Requests from unauthenticated users need not be logged. Thus, to reduce the number of logs produced by exodus-gw, exodus-gw should only log requests from authenticated users. This will eliminate noisy "login" logs caused by the readiness/liveness probes.

Do not log unauthenticated logins [RHELDST-19460]

---

tox.ini

JSON output shows better evidence that the dependency scanning is working properly. With --full-report we don't get a listing of the found packages and their versions.

Tweak 'safety' command to use JSON by default

---

exodus_gw/routers/cdn.py
tests/routers/test_cdn_access.py

This commit adds a query parameter to the cdn_access route, defaulting to '/*', that allows users to specify a resource when generating a signed CDN URL.

Allow cdn_access resource specification [RHELDST-18242]

---

exodus_gw/aws/dynamodb.py
exodus_gw/worker/publish.py
tests/aws/test_dynamodb.py

Previously, DynamoDB write retries were oblivious to deadlines, which meant that, typically, the retry attempts would have to be exausted before a task could be marked as expired. With exponential backoff on retries, hours of retrying could elapse before an expired task was realized.
This commit sees that DynamoDB clients are aware of and do not exceed deadlines set by callers. This happens by calculating the remaining seconds before the deadline and using that value as the retries' max_time, which is resepcted by backoff's wait generators as well.

Retries respect deadlines [RHELDST-18193]

---

exodus_gw/settings.py
exodus_gw/worker/deploy.py
exodus_gw/worker/publish.py

Previously, actors had the ability to retry with exponential backoff. This commit adds the 'max_backoff' option to appropriate actors, preventing actors from backing off for intervals longer than determined by the actor_max_backoff setting (default 5 minutes).

Add max_backoff to dramatiq actors [RHEDLST-18193]

---

exodus_gw/logging.py
exodus_gw/settings.py
tests/test_logging.py

To track the healthiness of workers in OCP, we'll probe for a specific
file, checking it's latest update time and restarting should a certain
time elapse since that update.
This commit implements the necessary mechanism for writing that file.
By using a custom logging handler, we implement an emit method to log
updates the healthcheck file. The location of the healthcheck file can
be configured via a new setting, "worker_health_filepath".

Add logging handler to write to healthcheck file [RHELDST-19614]

---

exodus_gw/logging.py
exodus_gw/main.py
requirements.in
requirements.txt
test-requirements.txt
tests/app/test_db_session.py
tests/routers/test_common.py
tests/routers/test_publish.py
tests/routers/test_service.py
tests/routers/upload/test_head.py
tests/routers/upload/test_manage_mpu.py
tests/routers/upload/test_upload.py

Previously, it was unclear which messages were logged for which request. Now, using the new 'request_id' field, one can match log messages that are associated with a particular request.

Add request/correlation IDs to log messages [RHELDST-18313]

---

tox.ini

The requirements.txt/test-requirements.txt files are pip-compiled using python 3.9, which means they are not necessarily expected to work for any other python versions. This is potentially a problem for the dev-{worker,server} envs, which did not declare any python version and therefore would use whatever was the default in the calling environment.
In practice, if the caller uses python3.11, installation has started to fail with a ResolutionImpossible error due to:
The user requested greenlet==2.0.2
gevent 23.9.1 depends on greenlet>=3.0rc3; platform_python_implementation == "CPython" and python_version >= "3.11"
(in other words: requirements.txt asks for greenlet==2.0.2 and gevent 23.9.1, this is possible on python 3.9, but on python 3.11 gevent 23.9.1 requests greenlet>=3.0rc3, making …

Fix inability to launch dev-worker/dev-server on python3.11

---

docs/conf.py
scripts/gen-openapi
tox.ini

Previously we relied on Sphinx to overwrite build files with those listed in html_extra_files, specifically api.html. However, for some reason, that is no longer happening. This commit adds a copy command to the gen-openapi script to ensure that the appropriate files are present in the final build.

Ensure openapi files are copied to docs [RHELDST-19887]

---

exodus_gw/main.py
tests/app/test_request_id.py

This commit moves the addition of CorrelationIdMiddleware to the end of main.py so that it's invoked first and the ID is added across the entire application. Additionally a custom correlation ID validator was added to prevent validation errors when the middleware encounters its own IDs, e.g., retries.

Move correlation_id middleware and add validator [RHELDST-18313]

---

exodus_gw/aws/client.py
tests/aws/test_client.py

It was discovered that boto client configuration supports two retry attempt settings. The one used previously is not inclusive of the initial attempt so `"max_attempts": 1` means one retry will be attempted. This commit changes this setting to "total_max_attempts" because it is 1) preferred by the library and 2) inclusive of the initial attempt.
This directly addresses the intermittent UnseekableStreamErrors seen recently. These errors are only raised when boto attempts to retry S3 uploads, which we were unknowlingly commanding it to do.
Additionally in this commit, a key-value pair is added to the client's request to prevent redirects if/when botocore's newest redirector class is used.

Update S3ClientWrapper to prevent retries [RHELDST-20355]

---

tox.ini

I'm not exactly sure where the problem is, but for some time now when running dev-worker locally I'm seeing dramatiq decide to repeatedly reload as if some file is being continuously changed. This might be triggered by VS Code somehow.
The alternative polling-based backend seems perfectly stable, so use that instead.

dev env: use alternative dramatiq --watch backend

---

exodus_gw/models/dramatiq.py
exodus_gw/models/publish.py
exodus_gw/models/service.py
exodus_gw/models/sqlite_compat.py
tests/migrate/test_migrations.py

While working on one issue I noticed that "alembic autogen" was not clean, i.e. it wanted to generate some migrations even though I'd not changed the model, indicating some drift between the two.
There were two issues, both fixed, and in both cases treating the migrations as correct and the model as the place to be fixed.
1. In cfa6812 (upgrade to sqlalchemy 2.0), the "nullable" state of various columns was unintentionally changed.
Take tasks.deadline as an example. In our migrations, the column was always created as nullable=True. In the model, it was declared as a Mapped[datetime] with no specific 'nullable'; but per [A], that means it's derived from the type hint. Optional means nullable and non-Optional means not nullable, which makes sense. Hence that commit actually changed the …

Fix mismatch between sqlalchemy model and migrations

---

exodus_gw/migrations/test.py
exodus_gw/migrations/versions/0d88322fe0b3_.py
exodus_gw/migrations/versions/be804e93d51d_.py
exodus_gw/models/__init__.py
exodus_gw/models/service.py
exodus_gw/routers/publish.py
exodus_gw/worker/publish.py
tests/migrate/test_migrations.py
tests/routers/test_publish.py
tests/routers/test_service.py
tests/test_models.py
tests/worker/test_cleanup.py
tests/worker/test_publish.py

Previously the Task model had a publish_id column which was nullable, because some tasks relate to specific publishes (e.g. commit) and others do not (e.g. deploy-config).
For RHELDST-20490 I'd like to add some more columns which are specific to commit, but it's not really a good practice to dump all type-specific columns into a single table and allow them to be nullable. Inheritance can be used to instead have Task as the base class and CommitTask as a subclass adding additional fields, so let's do that.
The added migration includes usage of a recently added `tested_by` helper which allows tests to add data into the DB just before the migration runs. The migration tries to maintain all existing task objects correctly, and the test data helps ensure that this works. This also uncovered …

refactor: move commit tasks into their own table

---

exodus_gw/migrations/versions/1d51b80e64ba_.py
exodus_gw/models/__init__.py
exodus_gw/models/publish.py
exodus_gw/models/service.py
exodus_gw/routers/publish.py
exodus_gw/worker/publish.py
tests/routers/test_publish.py
tests/worker/test_publish.py

Internally, items have always been categorized into either phase1 or phase2 during commit, with phase2 being committed last. This is needed to ensure, for example, that a repomd.xml is not committed until after all other files referenced by it have been committed.
This change now documents that concept and exposes it via the API. By default, clients get the same behavior as always, but they can now also explicitly request a phase1 commit.
A phase1 commit writes phase1 items to the DB, same as always, but then stops without proceeding to write phase2 items. It also leaves the publish open for later modifications and a later phase2 commit.
This will be used to solve the following Pub/rhsm-pulp/exodus-gw integration problem:
Imagine that you need to publish multiple Pulp yum repos. You want …

Introduce concept of phase1 commit [RHELDST-20490]

---

exodus_gw/aws/dynamodb.py
exodus_gw/migrations/versions/fbac38695a01_.py
exodus_gw/models/publish.py
exodus_gw/routers/publish.py
tests/aws/test_dynamodb.py
tests/conftest.py
tests/routers/test_publish.py

All items written to DynamoDB are sorted by from_date.
Up to now, we have always taken the from_date from the time at which the commit task was enqueued. This means if two publishes would try to update the same path at the same time, whoever commits last "wins".
Those semantics are in fact not the most useful, which was exposed once realistic Pulp usage occurred. The problem is that it allows a sequence like the following:
1. Repo publishes within exodus-gw publish A.
2. Repo publishes again, within exodus-gw publish B.
3. Publish B is committed.
=> new state: repodata from (2) is available on CDN (which also contains packages added at step (1))
4. Publish A is committed.
=> new state: repodata from (1) is available on CDN.
BUG! repodata has effectively gone backwards, "unpublishing" …

Set from_date from item update time [RHELDST-20491]

---

exodus_gw/aws/util.py
exodus_gw/main.py
exodus_gw/routers/upload.py
tests/routers/upload/test_head.py
tests/routers/upload/test_upload.py

Any error responses from S3 would be previously caught by our generic exception handler and turned into a 500 internal server error.
We shouldn't do that, instead we should be giving the real error codes from upstream S3 back to the exodus-gw client so that:
- if the error is the client's fault, they can see the reason for that (e.g. BadDigest)
- if the error is of a type expected to happen during the course of normal S3 usage, make sure the client can see that error properly so that they can retry as normal (e.g. SlowDown)
- errors from S3 don't drag down the SLI of our service
This commit adds a new exception handler which passes back any upload errors using the proper status and error response.
Note that head_object already had special handling for this, specifically for 404 errors, …

Pass S3 error codes back to client [RHELDST-20675]

---

exodus_gw/database.py
tests/worker/test_cleanup.py

We are required to log outbound connections.
To achieve this for DB connections we've currently enabled sqlalchemy connection pool logging at DEBUG level, but that includes a lot of annoying log spam as well.
sqlalchemy has an events system which allows us to explicitly hook into connection events. Let's use that so we can arrange for connection logs at INFO level without having to enable logging of all other connection pool events.

Improve DB connection logging

---

exodus_gw/aws/client.py
exodus_gw/aws/log.py
exodus_gw/worker/autoindex.py
tests/aws/test_logs.py

We're required to log outbound connections.
Currently, for requests to AWS we achieve this by bumping the botocore.endpoint logger to DEBUG level.
This works, but it includes a lot of unwanted detail including some things which probably shouldn't go into the logs, such as request signatures.
Let's arrange for some logging of the requests via event handlers under our control. This allows us to log exactly what's needed. Request and response logs are both added, using different loggers so they can be toggled independently.

Improve boto/AWS logging

---

exodus-gw.ini
exodus_gw/routers/cdn.py
tests/routers/test_cdn.py

Rather than depending on exodus-cdn to generate its own signatures to
complete the redirection, generate the signatures here and forward them
with the redirect request. This should improve runtime and allows us to
remove code in exodus-cdn (lambda) that's present here.

Include content & origin signatures in redirect request [RHELDST-18071]

---

exodus_gw/routers/cdn.py
tests/routers/test_cdn.py

According to https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html#private-content-custom-policy-statement

CDN Redirect: policy resources must escape '?' [RHELDST-18071]

---

exodus_gw/routers/publish.py

This API doesn't load/return the "items" list on a publish. The way this was explained before was not appropriate for a user-oriented doc.
The reference to noload() in particular is a very inappropriate detail since a user of the exodus-gw API does not need to know or care that SQLAlchemy is used, or even that an SQL-based DB is used.
(We probably should have made this API just not return the 'items' element at all, instead of an empty list, but it's a bit late for that now.)

docs: tweak language regarding items on "Get Publish"

---

exodus_gw/worker/autoindex.py
tests/worker/test_autoindex.py

The special object key of "absent" is used on an item to effectively delete it. The autoindex code didn't filter these out, so when it saw e.g. a repodata/repomd.xml having key "absent", it would really try to fetch that object and generate an index, causing commit to fail.

Fix crash during commit if attempting to delete an entrypoint

---

exodus_gw/routers/publish.py
exodus_gw/routers/service.py
exodus_gw/schemas.py

Primarily, fix some examples completely missing from the docs. I'm not sure if this changed at some point, but per [1] it is necessary for examples to be placed under a "value" key in some contexts (and not others).
Also some minor improvements:
- use more realistic env name of "live" rather than "prod" in one example
- provide an example for task "links" so that the link to self can be seen
- set a specific example for updated/deadline dates on task, because the autogenerated example used the exact same datetime for both which is not realistic.
[1] https://swagger.io/docs/specification/adding-examples/

docs: improve/fix various examples

---

exodus_gw/main.py
exodus_gw/routers/upload.py

- use more realistic environment names which give a better idea of how they are used in practice.
- in the boto code example, don't refer to exodus-gw.ini. The target audience of the API docs are exodus-gw *users*, not exodus-gw *owners*. The users are not expected to know the details of exodus-gw's configuration files.
The concept of "Environments" is already explained in the API docs, so the text should simply reference that.

docs: minor edits to API doc text

---

exodus_gw/routers/service.py
tests/routers/test_common.py
tests/routers/test_service.py

Since there is no API at "/", previously if opening up the service in a browser, one would see a 404 Not Found error in JSON format. It gives the impression that there might be something wrong with the service.
Let's make it so that accessing the root of the service will redirect to the docs to fix this and help with discoverability of the API.
This logic is limited to browsers (judged by clients requesting an HTML response) so that other clients wouldn't come to depend on it.

docs: redirect from root of service to /redoc

---

exodus_gw/dramatiq/broker.py
exodus_gw/dramatiq/middleware/__init__.py
exodus_gw/dramatiq/middleware/correlation_id.py
tests/dramatiq/test_broker.py
tests/dramatiq/test_worker.py

The asgi_correlation_id log filter is enabled even in the dramatiq worker, but so far it always logged "request_id": null since the id was not propagated in any way.
This commit adds another dramatiq middleware to automatically propagate it. This allows matching up logs from a worker's task with logs from whichever HTTP request spawned that task, which previously has sometimes not been possible. asgi_correlation_id itself already maintains an extension to do this with celery, so it seems propagating the id into background tasks is an intended usage.

logging: propagate correlation ID through dramatiq

---

exodus_gw/routers/publish.py
exodus_gw/worker/__init__.py
exodus_gw/worker/autoindex.py
tests/routers/test_publish.py
tests/worker/test_autoindex.py

autoindex step formerly happened only during the commit actor. The indexing of a yum repo needs to do several requests to S3. For a typically sized repo it can take about 3-4 seconds on average. If a publish contains hundreds of repos, this means the total autoindex time might measure in the tens of minutes, which can dominate the time needed to commit.
There's no technical reason why the autoindex step has to wait until commit; it was only written that way since it was convenient to do so. It would be better if the work could be done prior to commit.
It's possible to do an autoindex on a specific repo as soon as that repo's entry points / repodata have been added to the publish, so let's start doing that: when an entry point is added, a background autoindex actor is triggered to do …

autoindex in the background for improved performance [RHELDST-22148]

---

exodus_gw/models/publish.py
exodus_gw/routers/publish.py
exodus_gw/schemas.py
tests/routers/test_publish.py

Links were previously resolved only at commit time. In most cases, we have all the needed info to resolve links as items are being added to a publish:
- if items being added are links to items which already exist in the DB, they can be immediately resolved before saving.
- if items being added are targets of links which already exist in the DB, those existing items in the DB can be updated as part of the current request.
This change adds the needed logic to resolve links during update for the above two cases. The motivation is that, per observations during a very large publish in RHELDST-22147, it was seen that some requests to "/commit" took as long as 60 seconds. This probably indicates that we're trying to do too much work in the context of a single HTTP request and it's better to find …

Improve performance via partial link resolution [RHELDST-22147]

---

exodus_gw/routers/publish.py

A couple of places where a Publish was locked FOR UPDATE can safely use shared locks rather than exclusive locks:
- when adding publish items, we want to lock the Publish to ensure it remains in PENDING state during our update. But we won't actually change the state of the Publish, so we only need a read/shared lock.
- similarly during commit, we want to lock the Publish to ensure it's in PENDING state. In phase2 commit, we actually then update the state of the Publish, so we need an exclusive lock. In phase1 commit we don't modify the Publish and it's safe to use a read/shared lock.
When using the postgresql dialect, "read=True" here maps to "FOR SHARE" which is documented at [1].
This change is meant to improve performance by eliminating some scenarios where a request would have had to …

Minor locking tweaks to reduce contention

---

exodus_gw/models/publish.py

This conditional was added as an escape hatch just in case the bug fix for RHELDST-21893 broke some exodus-gw users and would have to be temporarily disabled. In practice we never needed to use this and it can be cleaned up. Link isolation should always be enabled, as originally intended.

cleanup: drop unused LINK_ISOLATION hack

---

exodus_gw/dramatiq/broker.py
exodus_gw/dramatiq/middleware/db_ready.py
exodus_gw/dramatiq/middleware/pg_notify.py
exodus_gw/dramatiq/middleware/scheduler.py
exodus_gw/dramatiq/middleware/settings.py
tests/conftest.py
tests/dramatiq/test_pg_notify.py

Dramatiq actors are declared at import time, before our test fixtures have had a chance to set up the test DB. In order to ensure dramatiq points at the test DB, the prior solution was an autouse fixture which would create a new temporary broker pointing at the test DB and move all existing actors over to that.
There was a major issue with this which went unnoticed: all the middlewares were recreated each time. Since some of the middlewares work by wrapping the functions on the actors, this meant every test would add a new level of wrapped functions on top of those already set up by prior tests. Once the total number of tests exceeds some threshold, the number of chained functions would be high enough to cause a stack overflow.
This commit changes the approach used to point the broker at …

Fix dramatiq test issue leading to stack overflow

---

exodus_gw/dramatiq/middleware/log_actor.py
exodus_gw/logging.py
tests/dramatiq/test_worker.py

This commit revamps the LogActor dramatiq middleware to resolve some issues observed in the logs.
The main changes are:
- Instead of prefixing log messages with e.g. "[commit abc123]", put that info into proper fields rendered into our JSON logs, e.g. {"actor": "commit", "publish_id": "abc123", ...}
- Include the message ID (which we reuse as task ID). In the case of phase1 commits which can happen multiple times for a single publish, without logging the message ID we can't match up which logs came from which task.
- Produce generic start/stop/failed messages for every actor, which also include the actor's duration. Without this there was no clear way to tell when actors started and ended, since most of our actors themselves aren't designed to log that internally.
- In the JSON log …

Revise and improve actor logging

---

exodus_gw/models/publish.py
exodus_gw/routers/publish.py
exodus_gw/worker/publish.py

There are still DB deadlocks occurring from time to time. These all seem to be related to multiple rhsm-pulp repos updating records for the same files concurrently (e.g. multiple repos having the same RPMs will all need to update the same paths under /origin/ around the same time).
While the relevant code is all prepared to retry on deadlock anyway and so this should not be noticeable beyond a delay, it would be nice to fix this.
This commit tries to fix it by always applying a consistent order for all queries obtaining row locks on items. The change is speculative as I can't reproduce the deadlocks on demand, but it's consistent with the advice given in postgres docs[1]:
> The best defense against deadlocks is generally to avoid them by being
> certain that all applications using a …

Use ordered queries to reduce deadlocks [RHELDST-22078]

---

exodus_gw/settings.py

Without this, atomic behavior for kickstart repo publishes will not be achieved.

Ensure kickstart entrypoints are listed in default settings

---

exodus_gw/routers/publish.py
exodus_gw/settings.py
tests/routers/test_publish.py

RHELDST-22148 introduced the concept of a partial autoindex, which is triggered as soon as entry points are added onto a publish without waiting until commit.
This introduced a problem for kickstart repos. The problem is that a kickstart repo is simultaneously a valid yum repo, containing both yum and kickstart entrypoints. There is no guarantee in which order the client will add these onto a publish.
If the client added yum repodata first, partial autoindex could be triggered and successfully parse the repo as a yum repo (only). If the client then later added kickstart repodata, the autoindex would not be regenerated to include kickstart files, because the index is treated as immutable and assumed valid if it already exists on the publish.
This commit fixes the problem by effectively …

Fix missing files from kickstart indexes [RHELDST-22387]

---

exodus_gw/routers/cdn.py
tests/routers/test_cdn.py

The URLs used here for redirect ought to be percent-encoded.
Although neither CloudFront nor exodus-lambda care about this, if not encoded, some clients will break. python-requests is an example of a client which breaks (while curl is OK).
What happens with python-requests is like this:
1. python-requests caller requests the CDN redirect API with a path having a reserved character, e.g. /some^path
2. python-requests automatically encodes to /some%5Epath
3. starlette/gunicorn/whatever automatically decodes to /some^path, so that's what the exodus-gw code sees
4. exodus-gw responds with a redirect, with Location: <cdn_endpoint>/some^path
5. python-requests automatically encodes *that* to <cdn_endpoint>/some%5Epath when issuing the follow-up request
6. since the final URL for the request …

Add missing URL encoding during CDN redirect [RHELDST-22493]

---

tox.ini

python 3.11 is intended to be the primary python version used for testing and deployment of exodus-gw. Since we use that version to compile the dependencies, we should be using it in *every* tox env, as the deps may not be installable for other python versions.

Use python3.11 consistently in tox

---

exodus_gw/auth.py
exodus_gw/aws/dynamodb.py
exodus_gw/aws/log.py
exodus_gw/aws/util.py
exodus_gw/dramatiq/middleware/scheduler.py
exodus_gw/migrations/test.py
exodus_gw/models/dramatiq.py
exodus_gw/models/publish.py
exodus_gw/models/service.py
exodus_gw/routers/deploy.py
exodus_gw/routers/publish.py
exodus_gw/routers/service.py
exodus_gw/routers/upload.py
exodus_gw/schemas.py
exodus_gw/settings.py
exodus_gw/worker/autoindex.py
exodus_gw/worker/deploy.py
exodus_gw/worker/publish.py
tests/app/test_db_session.py
tests/aws/test_logs.py
tests/conftest.py

exodus-gw uses python 3.11. From python 3.10 onwards, type hints can be simplified in various ways, but this was not taken advantage of here. Update all the code to consistently use a more modern form:
- container classes like `typing.List` are no longer needed, the builtin containers like `list`, `dict` can be used directly.
- `Union[x, y]` can be written `x|y` without any imports
- `Optional[x]` can be written `x|None` without any imports
- some features of `typing` have been moved to `collections.abc`

Modernize type hints

---

exodus_gw/docs.py
exodus_gw/main.py

The built-in docs are worded in a generic way; e.g. since authentication is beyond the scope of exodus-gw itself, the doc string under that section vaguely suggests to consult "internal documentation".
Internal users need a way to actually find the docs relevant to them, so let's allow these sections to be customized. Let the doc strings use env var substitution. This means we can set an environment variable to link to proper internal docs about authentication, or to explain that the specific deployed environments are "pre" and "live", etc.

docs: allow for customization of the application's main doc string

---

exodus_gw/routers/publish.py
exodus_gw/settings.py
tests/routers/test_publish.py

Previously, exodus-gw's publish APIs allowed any authorized user to publish to any paths within a given CDN environment.
Now, it is possible to restrict individual users to publishing to certain paths in a given CDN environment using the publish_paths setting, or the EXODUS_GW_PUBLISH_PATHS environment variable.
An example of the publish paths config:
{
"pre": {
"fake-user": [
"^(/content)?/origin/files/sha256/[0-f]{2}/[0-f]{64}/[^/]{1,300}$"
],
},
"live": {
"fake-user": [
"^(/content)?/origin/files/sha256/[0-f]{2}/[0-f]{64}/[^/]{1,300}$"
],
}
}
Any clients identified in the config are authorized to publish to any path which matches the defined regex. When a client attempts to publish to a path to which does not match the defined regex, they will get a 403 response. Any client which is …

Introduce per-user path restrictions [RHELDST-23442]

---

exodus_gw/worker/publish.py
tests/aws/test_dynamodb.py
tests/conftest.py
tests/worker/test_publish.py

The automatically generated directory listings are a form of entry point
and ought to be treated as phase 2 content, like the rest of the entry
points. If this is not done, it means that (e.g.) yum repodata and the
directory listings generated from it are not guaranteed to be committed
together, and so may sometimes become out of sync with each other.
Tweak the publish code to treat these files in the same way as any other
entry point file.

Fix autoindexes treated as phase 1 content [RHELDST-23816]

---

exodus_gw/routers/publish.py
tests/routers/test_publish.py

In order to prevent conflicts, ensure that all clients follow the correct usage of the /origin/files/sha256 structure.
When clients publish underneath the /origin/files/sha256/ path, it is enforced that:
(1) The path always matches this format:
/origin/files/sha256/(first two letters of sha256sum)/(full sha256sum)/(basename)
(2) Every object_key is either absent, or is equal to the full sha256sum present in the path.
When either rule is broken, the request is denied with a 400 response.

Enforce /origin/files invariant [RHELDST-23443]

---

examples/update-config

The update-config example generates new config from product service and posts it to deploy-config.
Let it also read config from a JSON file. This makes it an easy way to test the deploy-config endpoint with arbitrary canned config.

examples/update-config: support loading from file

---

exodus_gw/routers/upload.py
tests/routers/upload/test_upload.py

When an object is uploaded to S3, uploading entity(uploader) info i.e user or service account is recorded as "gw-uploader" in the object metadata. This provides an additional source for auditing uploaded content apart from logs.

Record uploader info in S3 metadata during upload [RHELDST-234411]

---

exodus_gw/worker/cache.py
tests/worker/test_cdn_cache.py

It turns out there is a special case in the current CDN config forcing a fast 404 response on treeinfo URLs not ending in "/kickstart/treeinfo". A side-effect of forcing that response is that any requests to cache flush on such a path will fail, e.g.
flush /some/kickstart/treeinfo => OK
flush /some/treeinfo => always fails
As such, we'll need a special case to filter out these paths from any attempted cache flushes. There is never any need for cache flush if the response is forced to 404 anyway.
Note this is unlikely to come up in any real publishes of kickstart repos since those are always using /kickstart in the path. It came up in the context of migrating some old content to exodus-cdn, because some files named "treeinfo" exist underneath /origin/files which will trigger the usual …

cache: skip non-kickstart treeinfo [RHELDST-24308]

---

.safety-policy.yml
exodus_gw/worker/cache.py
exodus_gw/worker/deploy.py
exodus_gw/worker/publish.py

Fix up a couple of issues which had caused CI to become blocked:
- safety started to complain about a Jinja CVE (which should be suppressed)
- mypy started to detect an existing issue, add asserts to resolve

CI fixes [2024-07]

---

exodus_gw/aws/dynamodb.py
exodus_gw/models/dramatiq.py
tests/worker/test_deploy.py

This commit partially reverts db4a3443feadd74cb; specifically, it disables the writing of compressed config and reverts back to writing JSON config as before.
This is being reverted due to an issue noticed during testing. It seems that the written items are ending up with *two* layers of base64 encoding, which is not intended.
The boto docs[1] use base64 strings as example arguments, giving the impression the caller is expected to take care of base64 encoding, but in fact botocore internally does the encoding; if the client also encodes, we end up with two layers of encoding.
There is also a bug filed relating to this[2].
The code here still seems to "work" since the same mistake is made on both the writing and reading end, but the goal is to make the config smaller and having …

revert (partial): write compressed configuration [RHELDST-25461]

---

exodus_gw/aws/dynamodb.py
tests/conftest.py
tests/worker/test_deploy.py

This commit re-enables the writing of compressed config, this time without the extraneous layer of base64 encoding, as this is understood to be done implicitly by botocore.
Must be merged *after* deployment of corresponding exodus-lambda change: https://github.com/release-engineering/exodus-lambda/pull/589

Write compressed config, round 2 [RHELDST-25461]

---

exodus_gw/aws/dynamodb.py
exodus_gw/aws/util.py
tests/aws/test_uri_alias.py
tests/worker/test_cdn_cache.py
tests/worker/test_publish.py

It was intended to take RHUI aliases into account during cache flush, but this was not implemented correctly.
The main issue was that alias resolution was only implemented in the direction of (src => dest), but in the case of RHUI, we are always publishing content on the destination (non-RHUI) side of the alias. Hence we need to also consider the aliases in the (dest => src) direction to figure out that the src (RHUI) side of the alias is relevant for cache flush.
A second issue was that, if multiple aliases were involved in a path, we would not flush cache for all of them. This couldn't work because the uri_alias function was designed to return only a single value, after resolution of all aliases. When multiple aliases are in play, content is actually accessible at all the paths …

Fix rhui_alias resolution during cache flush [RHELDST-26143]

---

docs/deployment.rst
exodus_gw/settings.py
exodus_gw/worker/cache.py
tests/worker/test_cdn_cache.py

This change extends the cache flush config to support separate rules with different templates, enabled via patterns matched against candidate paths for flush.
The goal here is to reduce the amount of unnecessarily flushed URLs/ARLs. In typical scenarios, we have three different CDN hosts in front of a single exodus-gw environment, with certain subtrees being only available from certain hosts. With the flat config structure existing before this change, we had no choice but to flush cache keys for all three of them for every path, even though each path is only relevant to one of the hosts. Hence, we were flushing 3x as many ARLs as we should be.
With this change we can update the configuration to only flush cache for the necessary CDN host for each subtree, significantly cutting down the …

Introduce cache flush rules [RHELDST-26144]

---

.pre-commit-config.yaml

Black requires Python 3.9+ to run. The installation of the black pre-commit environment currently fails with:
`RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'`
This commit upgrades the target Python verison used by the pre-commit hooks to 3.11, the minimum Python version required by exodus-gw.

Upgrade python version used by pre-commit hook

---

exodus_gw/aws/dynamodb.py
exodus_gw/aws/util.py
exodus_gw/routers/config.py
exodus_gw/routers/deploy.py
exodus_gw/schemas.py
exodus_gw/worker/cache.py
exodus_gw/worker/deploy.py
tests/aws/test_uri_alias.py
tests/conftest.py
tests/routers/test_config.py
tests/worker/test_cdn_cache.py
tests/worker/test_deploy.py

Certain paths on our NetStorage fs have no symlinks/aliases, and teams/tools that make use of these paths expect similar behaviour from exodus.
This change introduces "exclude_paths" to exclude alias generation for certain paths, so we can replicate NetStorage behaviour.

Add exclusions for aliases [RHELDST-26013]

---

scripts/systemd/exodus-gw-sidecar.service

The `{env}-config-consumer` role was introduced along with the "GET /{env}/config" endpoint. Make sure the role is granted to the test user in the development environment so that it can be accessed there.

dev-env: add missing role for config getter endpoint

---

exodus_gw/settings.py
exodus_gw/worker/publish.py
tests/worker/test_publish.py

Kickstart repos don't adhere to the "mutable entry point, immutable
everything else" design of other content types, such as yum and
file repos. For example, files such as "/EULA", "/images/install.img"
may receive in-place updates.
As such, the usual categorization between phase1 and phase2 content
based on entry points does not fit these repos correctly.
From the point of view of exodus-gw, the set of files receiving
in-place updates is arbitrary, so we'd better treat them *all* as phase
2 content and try to update them together. RPM files are the only
exception, as we still expect that an RPM published to the same
path is always the same thing.
The effects of categorizing kickstart files as phase2 content include:
- on publish, CDN cache will now be flushed for all non-RPM kickstart …

Mark all kickstart non-RPM content as phase2 [RHELDST-28021]

---

exodus_gw/models/path.py
exodus_gw/models/publish.py
exodus_gw/worker/deploy.py
tests/worker/test_deploy.py

We saw some repo instability after a recent GA. This was due to only a portion of affected URLs being flushed. The current deployment cache flush only gets URLs based on directly updated aliases. This didn't take into consideration URLs that require several aliases to be applied.

Flush transitive aliases during deployment [RHELDST-28321]

---

exodus_gw/aws/util.py
exodus_gw/routers/config.py
exodus_gw/routers/deploy.py
tests/conftest.py
tests/worker/test_cdn_cache.py

It was noted that including the /images/ path can cause issues with kickstart repos as the path can occur within repos. This complication makes the path less appropriate for blanket exclusions. This change removes mentions of /images/ from tests to prevent later confusion.

 Fixup: remove mentions of /images/  [RHELDST-26015]

---

exodus_gw/aws/dynamodb.py
tests/conftest.py
tests/routers/test_config.py

Previously, exodus-gw would fail with a 500 error when attempting to use the "get config" endpoint (i.e., GET /{env}/config) against an environment with an empty config table.
Now, when attempting to use the "get config" endpoint against an environment with an empty config table, exodus-gw returns a default object representing a valid empty config.
```
$ curl -s --cert ~/certs/$USER.crt --key ~/certs/$USER.key \
https://localhost:8010/test/config | jq
{
"listing": {
"": {
"var": "releasever",
"values": [
""
]
}
},
"origin_alias": [
{
"src": "",
"dest": "",
"exclude_paths": []
}
],
"releasever_alias": [
{
"src": "",
"dest": "",
"exclude_paths": []
}
],
"rhui_alias": [
{
"src": "",
"dest": "",
"exclude_paths": []
}
]
}
```

Get config endpoint returns valid empty config [RHELDST-28276]

---

scripts/systemd/exodus-gw-cert.service
scripts/systemd/exodus-gw-db.service

The postgres image used in the dev env (quay.io/exodus/postgres:12) is an Alpine-based image. The image tag has been updated to clarify that the exodus-gw-db image used in the dev env is Alpine-based (quay.io/exodus/postgres:12-alpine).
Using the Alpine-based image without any changes to the dev env configuration produces the following error:
`FATAL:  private key file "/var/lib/postgresql/db-service-key.pem" must be owned by the database user or root`
Previously, we used a Debian-based postgres image wherein the standard postgres UID was 999. In Alpine-based images, the standard postgres UID is 70. The dev env configuration has been updated to reflect the UID discrepancy.

Dev env updates for Alpine-based db image [RHELDST-29655]

---

requirements.in
requirements.txt
test-requirements.txt

pydantic conflicts are repeatedly breaking CI checks, so lock version to latest

Lock pydantic version to fix recurring conflicts

---

exodus_gw/routers/upload.py
tests/routers/upload/test_manage_mpu.py
tests/routers/upload/test_upload.py

In upload's `_already_uploaded` helper function, the `head` endpoint was called rather than directly calling S3's `head_object` function, but the response from `head_object` was expected rather than that of the `head` endpoint. This led to uncaught 404 codes resulting in push errors.
This commit corrects this mistake by directly using the AWS S3 sdk in helper functions `_already_uploaded` and `_ensure_aborted`, avoiding using exodus-gw endpoints within endpoints entirely, so the anticipated errors are handled appropriatly.

bug-fix: incorrect error expected in upload helper [RHELDST-30644]

---

exodus_gw/routers/upload.py
tests/routers/upload/test_manage_mpu.py
tests/routers/upload/test_upload.py

To help prevent duplicate upload operations, this commit adds a check for an s3 object's existence before attempting a multipart_put or complete_multipart_upload. If the object does already exist, an abort of the multipart upload is attempted to avoid overwriting the previous object and orphaned parts are cleaned up.

upload, multipart: abort if object already exists [RHELDST-30644]

---

exodus_gw/routers/upload.py
tests/routers/upload/test_manage_mpu.py

When aborting an attempt to complete multipart upload, the returned response attempted to access "Key" from the head_object response but it isn't provided by the s3 API. Instead, it should use the local key variable.

Fix multipart_upload: 'Key' unavailable in head response [RHELDST-30644]

---

.github/workflows/pip-compile.yml

Pin pip to <=25.0 in GitHub Actions to avoid issues introduced in pip v25.1

ci: pin pip version in workflow [RHELDST-31877]

---

.github/workflows/pip-compile.yml
tox.ini

* revert the previous attempt in workflow setting
* pin pip version in tox.ini

Temporary fix for broken pip-compile [RHELDST-31877]
