release-engineering/exodus-gw

- docs/deployment.rst
- exodus-gw.ini
- exodus_gw/app.py
- exodus_gw/settings.py
- tests/test_logging.py
Adds loglevels section to exodus-gw.ini which is parsed and loaded by
the settings.get_settings function and applied upon app startup.
> Make logging levels configurable [RHELDST-3456]

- .github/workflows/linting.yml
- examples/s3-upload
- exodus_gw/auth.py
- exodus_gw/s3/util.py
- pyproject.toml
- scripts/gen-openapi
- setup.py
- tests/auth/test_call_context.py
- tests/auth/test_roles.py
- tests/conftest.py
- tests/s3/test_client.py
- tests/s3/test_manage_mpu.py
- tests/s3/test_upload.py
- tests/settings/test_get_settings.py
- tests/test_exception_handler.py
Refactoring the linting workflow to use a marketplace Action + validation imports order with isort.
> Use 'Python Code Quality and Lint' Action for flake8+isort

- docker-compose.yml
It is useful for functional testing in CI and local dev environment.
BTW, docker-compose.yml file can be consumed by docker-compose and by podman-compose.
> A docker-compose file for orchestrating a local dev environment

- exodus_gw/main.py
- tests/test_logging.py
Resolves an issue wherein log messages weren't output.
> Add logging handler [RHELDST-3456]

- exodus_gw/crud.py
- exodus_gw/models.py
- exodus_gw/routers/gateway.py
- exodus_gw/schemas.py
- tests/conftest.py
- tests/routers/test_gateway.py
- tests/test_models.py
Includes introduction of the Item schema and model and the Publish
model's items attribute.
Co-authored-by: lioramilbaum <lmilbaum@redhat.com>
> Implement update_publish_items endpoint [RHELDST-2160]

- exodus_gw/worker/broker.py
- tests/worker/test_broker.py
Commit 6c7b03200 made sqlalchemy and dramatiq share DB sessions.
To make this asyncio-safe, a contextvar was used to hold the current
session during an HTTP request. However, the implementation broke
the background worker process, which would raise an error like this
on startup:
LookupError: <ContextVar name='pool' at 0x7fe3effd2630>
My mistake was thinking that the current context is swapped only
when switching coros and not when switching threads. Turns out
it's swapped at both, which means that the dramatiq worker would
lose its reference to the pool when booting up new worker threads.
To fix this, make the broker use a ContextVar only after it has
been asked to use an sqlalchemy session. This makes the overall
behavior as follows:
- within the web component, the broker uses a …
> Fix LookupError in worker introduced by 6c7b03200

- examples/exodus-sync
- exodus_gw/routers/upload.py
- tests/routers/upload/test_head.py
Introduces a new upload endpoint using the HEAD operation which
retrieves metadata from an S3 object.
> Support S3 head_object operation [RHELDST-4705]

- exodus_gw/routers/upload.py
- tests/routers/upload/test_head.py
A 404 is normal when querying an object which doesn't exist,
which is one of the main use-cases of this API, so it doesn't
make sense to log it as an error. Let's log that one as a DEBUG
and log any other unsuccessful responses as an error.
> Tweak logs in HeadObject 404 case

- scripts/systemd/exodus-gw-sidecar.service
> Update sidecar image for dev env [RHELDST-3478]

- tests/routers/test_publish.py
Ensure we have at least one test of the endpoint which doesn't rely
on mocking, so we know the DB operations are being verified.
> tests: add an 'update publish items' test using TestClient

- examples/exodus-sync
- exodus_gw/settings.py
- exodus_gw/worker/publish.py
Initial time limit set to 30 minutes to accomidate large publishes.
> Add actor time limit setting [RHELDST-4973]

- exodus_gw/routers/upload.py
All the points have now been implemented, except one about
setting chunk size limits, but it's unclear if this is needed.
> cleanup: remove TODOs which are now done

- exodus_gw/main.py
- exodus_gw/routers/publish.py
- exodus_gw/schemas.py
- tests/routers/test_publish.py
Previously, paths for web_uri and link_to were accepted with or without
leading slash (/). This can cause problems matching up link_to paths
with web_uris or finding content via exodus-lambda.
Now all web_uri and link_to paths are normalized to clean up any
redundant separators or up-level references and to always have a leading
slash (/).
Additionally, all publish item validation was moved to the ItemBase
schema and, due to the issues it has continued to cause,
update_publish_items no longer accepts single items (i.e., 'items' must
now always be a list).
> Normalize URI and link target paths in publish items [RHELDST-9189]

- exodus_gw/schemas.py
- tests/routers/test_publish.py
It was detected that non-existent link_to values were wrongly being
validated. This commit corrects that by first checking the value's
existence and refactoring Item schema validation to favor simplicity.
> Fix: abspath check on empty/None link_to values [RHELDST-9189]

- exodus_gw/schemas.py
The performance of the validation method here is rather important as it runs on every item added to a publish; i.e. in typical scenarios for a large publish, it needs to run 10,000 times in a single HTTP request, since that's how many items we put per batch.
A few slow operations were repeated at each call: compiling regular expressions and parsing settings from environment variables. Pull them out into module-level constants so they are not recalculated at every validation.
In local testing this reduced the time for a "PUT /<env>/publish/<id>" operation with 10,000 items from ~3 seconds to ~1 second, or about a 2/3rds runtime improvement.
> Improve publish item validation performance [RHELDST-13473]

- exodus_gw/worker/scheduled.py
- tests/worker/test_cleanup.py
Previously, when loading Tasks and Publishes for scheduled cleanup operations, any children were automatically loaded as well, using more memory than necessary and causing crashes by exceeding the limits set in OpenShift.
This commit adds the noload option to cleanup queries with keys="*" so that no children are ever loaded.
Because children aren't loaded, publish items are no longer deleted automatically. So a delete query was added for items when cleaning up old publishes.
> Add noload option to cleanup queries [RHELDST-14737]

- exodus_gw/routers/publish.py
- tests/routers/test_publish.py
This commit implements a new endpoint to retrieve a publish from the service database. No items are returned with the publish as there is currently no use case for them and implementation would be non-trival.
> Add GET publish endpoint [RHELDST-14412]

- exodus_gw/dramatiq/middleware/log_actor.py
- exodus_gw/worker/publish.py
- tests/dramatiq/test_worker.py
Firstly, assign a meaningful thread name so it's easier to tell when log messages are coming from the BatchWriter.
Secondly, fix issues with the actor log message prefixing.
Log messages coming from within an actor are intended to be prefixed with the actor's name and task ID, e.g. "[commit cf2f...a3e]".
However, this wasn't working from within the BatchWriter helper class. The reason for this was that the logging middleware relied on a thread-local to maintain the current log prefix, but BatchWriter created new threads internally which would then see different values on the thread-local.
It can be solved by switching from a thread-local to the more generic contextvars.Context. It is possible to explicitly propagate a context from one thread to another to share the log prefix (or any …
> Fix some logging issues with BatchWriter [RHELDST-17783]

- exodus_gw/aws/dynamodb.py
Instances of this class are used from within multiple threads in BatchWriter, but the code was not written to be thread-safe (racy lazy initialization of some attributes). Fix it:
1) no lazy initialization for 'client'. If you're creating an instance of
this class, you're definitely going to use the client, so there is no
benefit to the added complexity of delaying initialization.
2) safe lazy initialization for 'definitions'. Not every usage of the
class might read definitions, so this can be lazy, however we should
use a lock to ensure it only happens once even when multiple threads
are using the object.
The motivation for this change: while reviewing localstack logs during commit operations, I found that there were many dynamodb Query operations at the beginning of a commit. This …
> Fix thread-safety issues in DynamoDB helper class

- exodus_gw/auth.py
- exodus_gw/aws/dynamodb.py
- exodus_gw/aws/util.py
- exodus_gw/deps.py
- exodus_gw/logging.py
- exodus_gw/migrate.py
- exodus_gw/routers/cdn.py
- exodus_gw/routers/deploy.py
- exodus_gw/routers/publish.py
- exodus_gw/routers/upload.py
- exodus_gw/worker/autoindex.py
- exodus_gw/worker/deploy.py
- exodus_gw/worker/progress.py
- exodus_gw/worker/publish.py
- exodus_gw/worker/scheduled.py
- tests/aws/test_dynamodb.py
- tests/aws/test_uri_alias.py
- tests/routers/test_publish.py
- tests/test_logging.py
In addition to formatting all logs as JSON, this commit makes timestamp
format configurable upon setting a "datefmt" key in log_config settings.
> Convert logging format to JSON [RHELDST-18175]

- exodus_gw/aws/dynamodb.py
- exodus_gw/worker/autoindex.py
- tests/aws/test_uri_alias.py
- tests/conftest.py
Snuck in a couple fixes for mypy typing complaints
> Resolve releasever aliases when publishing [RHELDST-18849]

- exodus_gw/aws/dynamodb.py
- tests/aws/test_dynamodb.py
Previously, batch_write would only attempt retries when encountering unprocessed items. This meant that lower-level errors (e.g., a temporary network outage between exodus-gw and DynamoDB) would not result in a retry.
Now, batch_write retries when encountering EndpointConnectionError exceptions and unprocessed items.
> Retry batch_write on 'EndpointConnectionError' [RHELDST-18585]

- exodus_gw/worker/autoindex.py
There is an S3ClientWrapper utility class which provides some default config to our S3 clients. One of the things it does is disable retries, for the reasons explained in RHELDST-20355.
However: those reasons only apply in the /upload API case where we are taking an HTTP request from a client and forwarding it to S3. It does NOT apply in the worker case, where the worker is acting as a regular S3 client with no special requirements or restrictions. Therefore it was inappropriate to use the config which disables retries here.
Change it to just construct an S3 client in the normal way, ignoring the wrapper. The one piece of logic we still need from the wrapper (respect the endpoint URL environment variable) is reproduced here.
This problem has been present for a long time, but prior to …
> Fix autoindex step unable to retry S3 requests [RHELDST-20662]

- exodus_gw/worker/autoindex.py
- tests/worker/test_autoindex.py
This code was missing the usual logic to do a HEAD request to check whether an object was already in S3 before uploading it. Add the missing logic.
This is important since object versioning is enabled, so each upload would create a new object version and incur an ongoing cost. In practice, indexes across many repos generate an identical object (e.g. the top level of every yum repo looks the same - just "Packages" and "repodata"), so the number of unwanted object versions created due to this is quite high. The aforementioned top level yum repo index object already has ~9000 or so versions in production.
> autoindex: don't re-upload existing objects [RHELDST-20661]

- exodus_gw/dramatiq/consumer.py
- tests/dramatiq/test_worker.py
The responsibility of updating a Task object to completed or failed generally lies within the dramatiq actor (e.g. the commit actor itself updates its corresponding Task).
However, there are some cases where that might not happen. One example is when a commit task fails at the autoindex step, as this happens before the main DynamoDB write step wrapped in try/finally. Another example would be openshift-level problems such as worker pods being killed with OOM in the middle of a task.
In such cases, a task may be left IN_PROGRESS even after a message failed to process. Our scheduled Janitor would eventually detect and fix that, but this is only intended to run every 12 hours or so, which is unreasonably long for e.g. Pub to learn that a task has failed.
To address this, at the same place …
> Fix tasks not promptly set to FAILED in some cases [RHELDST-20663]

- exodus_gw/routers/cdn.py
- tests/routers/test_cdn.py
Reverts release-engineering/exodus-gw#615
> Revert "CDN Redirect: policy resources must escape '?' [RHELDST-18071]"

- exodus_gw/models/publish.py
Items using link_to should only be resolved to a proper object within the current publish. If resolution is not limited in this way, it's even possible for links set up on "pre" to leak over into "live" or vice-versa.
Although link resolution was always intended to work this way since initially scoped, the fact that it was buggy ever since implemented means that unfortunately other systems might have come to rely on it, and Pub/Pulp in the "hook disabled" case is known to rely on it. For that reason, a temporary escape hatch is added to allow continuing with the original buggy behavior if needed.
There is no specific test in this repo targeting this bug, but there is a system test in pipeline-test repo covering it.
> Fix link resolution not isolated to current publish [RHELDST-21893]

- exodus_gw/worker/cache.py
- tests/worker/test_cdn_cache.py
The cache flush endpoint is intended to process aliases and to flush cache for the calculated URLs on *both* sides of alias resolution. The initial commit didn't include this. Add it now.
> Add alias resolution to cache flush endpoint [RHELDST-23276]

- tests/worker/test_deploy.py
The gzip compression function can produce inconsistent values in the header section. This change decompresses the config values to circumvent this variability.
> Address intermittent test failures [RHELDST-29699]

- exodus_gw/routers/upload.py
- tests/routers/upload/test_upload.py
To help prevent duplicate upload operations, this commit adds a check
for an s3 object's existence before attempting an upload. If the object
does exist, it aborts the current multipart upload and returns a
response with data from the existing object.
> multipart uploads: abort if object already exists [RHELDST-30644]

- exodus_gw/routers/upload.py
- tests/routers/upload/test_manage_mpu.py
Previously, when a duplicate upload was detected when trying to complete a multipart upload, an empty reponse was returned as in `abort_multipart_upload`. However, s3 apis expect an xml response. For compatibility and ease, this commit changes the response to the same as that produced by `complete_multipart_upload`, minus a few keys that are only available by the real CompleteMultipartUpload. This keeps things as "same" as they can possibily be while avoiding uploading duplicates/overwriting.
> multipart upload: make abort response same as complete [RHELDST-30644]

- exodus_gw/worker/deploy.py
- tests/worker/test_deploy.py
Problem: exodus-gw was expected to have triggered an automatic cache flush of the mainline kickstart paths after provisioning the CDN (i.e., after running a config deployment containing updated releasever aliases). This did not happen. This is because post-config deployment, exodus-gw only flushed paths that were prefixed by the alias src (i.e., the mainline repos) found in the PublishedPath db (which consists of recently published paths). The kickstart repos are only published to the dest side of the alias (i.e., DOT repos), so the kickstart paths will never appear in the PublishedPath db when we query for src paths.
To account for this, the post-deployment automatic cache flush behavior must flush paths on the "src" side of the alias, even if the PublishedPath db only contains paths on …
> Config deployment should flush resolved paths [RHELDST-32942]
